### ISSUE TITLE
error: the following arguments are required: DIR

### ISSUE THREAD

**Issue by 13270285331** [pytorch/examples#1004]
Excuse me，how can I deal with this problem？
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/58496897/167763473-f5d2a189-3ac5-4e77-9451-c6817065d5ed.png">

**Comment by msaroufim** [comment]
Hmm is this example from this repo? 

Regardless the error is on that you're missing a `DIR` param. Check out the code to get more clarity on what you're supposed to do
