### ISSUE TITLE
Accessing weights of a pre-trained model

### ISSUE THREAD

**Issue by nivi1501** [pytorch/examples#1010]
Hi, 
  Can you share how to print weights and biases for each layer of a pre-trained Alexnet model?

Regards,
Nivedita

**Comment by msaroufim** [comment]
This answer should help https://discuss.pytorch.org/t/access-all-weights-of-a-model/77672/2?u=marksaroufim

In general https://discuss.pytorch.org/ is a better forum for Q&A
