### ISSUE TITLE
Variable should be volatile when decoding. 

### ISSUE THREAD

**Issue by khanhptnk** [pytorch/examples#105]
translate.py can't be run with the same batch size as train.py. The reason is that intermediate variables are not destroyed without backprop and cause memory overflow. Specifying the input variable to be volatile solves this problem. 

https://github.com/pytorch/examples/blob/master/OpenNMT/onmt/Dataset.py#L31

**Comment by soumith** [comment]
OpenNMT has been moved to https://github.com/OpenNMT/OpenNMT-py and will be continuing development there by the OpenNMT team and other community members.

Please send pull requests and issues over there.

Thank you.
