### ISSUE TITLE
The order of the parameters is reversed. The two parameter (save_every, total_epochs)positions should be interchanged.

### ISSUE THREAD

**Issue by RuleNHao** [pytorch/examples#1074]
https://github.com/pytorch/examples/blob/35eb8149b57a1edc13a1baa6a6376ae9a4e1d664/distributed/ddp-tutorial-series/multigpu.py#L102

**Comment by RuleNHao** [comment]
It took me hours to find the bug. This is an unforgettable experience.

**Comment by RuleNHao** [comment]
And it also need to use `sampler.set_epoch()` method at the beginning of each epoch.

**Comment by suraj813** [comment]
@RuleNHao thanks for catching this! 

`set_epoch()` is an important suggestion to ensure random shuffling; thank you for bringing this up, I'll update the example to include this.
