### ISSUE TITLE
Need C++ L2 regularization example

### ISSUE THREAD

**Issue by bitnick10** [pytorch/examples#1075]
How to add L2 Regularization to a layer like keras
model.add(Dense(kernel_regularizer=regularizers.l2(0.01), activation='elu'))

**Comment by hudeven** [comment]
It's not supported. In PyTorch, you can achieve it by specifying `weight_decay` in optimizer. e.g. https://github.com/pytorch/examples/blob/f5bb60f8e6b2881be3a2ea8c9a3d43e676aa2340/imagenet/main.py#L194
