### ISSUE TITLE
Inconsistency b/w tutorial and the code

### ISSUE THREAD

**Issue by BalajiAI** [pytorch/examples#1101]
## 📚 Documentation

In the [DDP Tutorial](https://pytorch.org/tutorials/beginner/ddp_series_multigpu.html), there is inconsistency between the code in the tutorial and [original code](https://github.com/pytorch/examples/blob/main/distributed/ddp-tutorial-series/multigpu.py).

For example, under Running the distributed training job section,
the Trainer object should take train_data as an argument not dataset (in the original code, it is right).

The ideal PR to fix this issue is to make the tutorial consistent with the original code.

**Comment by hudeven** [comment]
cc @suraj813

**Comment by sudomaze** [comment]
@hudeven I am considering to work updating DDP Tutorial codebase, can you validate the implementation that I have here: https://github.com/sudomaze/ttorch/blob/main/examples/ddp/run.py

This was tested by multiple people. I am planning to make it more readable and add it to `pytorch/examples`. What are your thoughts?

**Comment by suraj813** [comment]
whoops missed this over the holidays - thanks for catching this @BalajiAI! Fixing this on the tutorials repo.

@sudomaze Hey Mazen 👋🏾, thanks for updating the tutorials! Your request might be better served as its own issue, do you mind opening a new one? thanks again!

Closing this thread as the OP's issue is resolved

**Comment by sudomaze** [comment]
Good to see you, @suraj813! 

I will start a new issue with the latest updated codebase and I might start new issues for more examples to add :D
