### ISSUE TITLE
🚀 Feature request / I want to contribute an algorithm

### ISSUE THREAD

**Issue by viveks-codes** [pytorch/examples#1111]
## Is your feature request related to a problem? Please describe.

Currently, PyTorch/examples does not have an implementation of the forward forward algorithm.[forward forward algorithm.](https://arxiv.org/abs/2212.13345)  This algorithm is a new learning procedure for neural networks and has promising approach to training neural networks, it is also becoming popular, because it's written by father of deep learning aka Geoffrey Hinton, its inclusion in PyTorch/examples would make it more accessible to a wider community of researchers  practitioners, and I would like to contribute in it❤️, I've Implemented This algorithm in my local notebook in pure pytorch❤️.I am new so please let me know How can I contribute this algorithm in this repo.

Thanks,
Vivek

## Describe the solution

The solution is to implement/add the forward forward algorithm in PyTorch/examples. This would include writing the code for the algorithm, as well as any docs or tutorial addition to the existing codebase.

## Describe alternatives solution

[https://keras.io/examples/vision/forwardforward/](https://keras.io/examples/vision/forwardforward/)

**Comment by soumith** [comment]
hi vivek, this sounds like a good example to have. would love to see your contribution.

**Comment by viveks-codes** [comment]
@soumith @msaroufim, could you kindly take a look at my pull request (https://github.com/pytorch/examples/pull/1114) and provide feedback? Thank you so much for your time and efforts! ❤️

**Comment by msaroufim** [comment]
I'll take a look, I haven't read the forward forward paper yet to give great feedback but planning on it today
