### ISSUE TITLE
word_language_model generate.py bug

### ISSUE THREAD

**Issue by AntonioDaSilva** [pytorch/examples#1116]
The README.md recommends the following line to generate text after training:

```
python generate.py --cuda --model Transformer # Generate samples from the trained Transformer model.
```

However, `generate.py` file's `argparse` do not have a `model` option. I ran it without `--model` option and it worked. Am I missing something?

**Comment by msaroufim** [comment]
Yeah seems a bit convoluted now, this should work with both models the corresponding `model.py` the RNN and transformer one. Since you found this, would you like to fix it? I can help merge your code
