### ISSUE TITLE
ImageNet preprocessing

### ISSUE THREAD

**Issue by cbasavaraj** [pytorch/examples#112]
Hi, in your ImageNet main.py code, you do not scale the training images to [0, 1], but go on to do normalization with means and std in this scale:

```
 normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                     std=[0.229, 0.224, 0.225])

```

but you do scale the validation images before normalisation:

`transforms.Scale(256),`

Any reason why?

**Comment by soumith** [comment]
You can see in Line 100 and 110, that both train and val datasets are normalized.

https://github.com/pytorch/examples/blob/master/imagenet/main.py#L100-L110

**Comment by cbasavaraj** [comment]
Thanks, but maybe my question was not clear. Both are normalised, but train is not scaled.

**Comment by fmassa** [comment]
@cbasavaraj The `Scale` transform resizes the image such that it's smallest size is 256.

**Comment by cbasavaraj** [comment]
Ok thanks! I thought `Scale` was for converting from [0, 255] to [0, 1]. But I see that that happens in `transforms.ToTensor()`.
