### ISSUE TITLE
About fast_neural_style

### ISSUE THREAD

**Issue by unhker** [pytorch/examples#1121]
How many rounds did you train in the fast neural style transfer experiment? I operate according to your steps, but the effect of the model I trained is not as good as the model you provided, and why is the model file I trained less than the file you provided by 3kb? I would like to know the reason and look forward to your reply!

**Comment by unhker** [comment]
The following are content pictures, style pictures, and migrated pictures in order. The result seems not very ideal. I would like to know why
![amber](https://user-images.githubusercontent.com/125473669/221613488-e6d80366-1574-49c6-b919-86d8c48d07d8.jpg)
![painting](https://user-images.githubusercontent.com/125473669/221614126-85a0f1fc-bd86-4191-935c-913cce29d31c.jpg)
![amber_princess3090](https://user-images.githubusercontent.com/125473669/221614178-ed7a2183-8166-4e43-979d-800aed5a80e5.jpg)

**Comment by unhker** [comment]
And why is the suffix of the model I trained named model and the suffix of the model I provided named pth? As shown below, mosaic.pth was provided by the author, and painting.model was trained by me. I want to know why the sizes and suffixes of these two files are different because my training model does not work well
![image](https://user-images.githubusercontent.com/125473669/227093622-eeda3c88-dd07-4d96-b98d-7e1c6006d5ec.png)

**Comment by katsully** [comment]
Was there an answer to this question?
