### ISSUE TITLE
parameter in word_language transformer model's last linear layer seems wrong

### ISSUE THREAD

**Issue by githarb** [pytorch/examples#1123]
in [model.py](https://github.com/pytorch/examples/blob/main/word_language_model/model.py) line 124 goes
```python
self.decoder = nn.Linear(nhid, ntoken)
```
But when I was checking a [similar tutorial by pytoch](https://pytorch.org/tutorials/beginner/transformer_tutorial.html), the model definition part goes
```python
self.decoder = nn.Linear(d_model, ntoken)
```
where  d_model is just ninp here and emsize in [main.py](https://github.com/pytorch/examples/blob/main/word_language_model/main.py) according to my understanding.
The reason why the code does not raise any exception is that the `emsize` and `nhid` params in [main.py](https://github.com/pytorch/examples/blob/main/word_language_model/main.py) are both set to 200 by default coincidentally. If change the nhid param to, say 300, the code raises an error.

**Comment by msaroufim** [comment]
Thanks for testing this throughly, I reverted the change https://github.com/pytorch/examples/pull/1124
