### ISSUE TITLE
memoryEfficientLoss does not split the batch dimension

### ISSUE THREAD

**Issue by khanhptnk** [pytorch/examples#113]
memoryEfficientLoss does not split the batch dimension, which is 1. 

https://github.com/pytorch/examples/blob/master/OpenNMT/train.py#L138

**Comment by soumith** [comment]
OpenNMT has been moved to https://github.com/OpenNMT/OpenNMT-py and will be continuing development there by the OpenNMT team and other community members.

Please send pull requests and issues over there.

Thank you.
