### ISSUE TITLE
If I am training on a SINGLE GPU, should this "--dist-backend 'gloo'" argument be added to the command?

### ISSUE THREAD

**Issue by HassanBinHaroon** [pytorch/examples#1229]
@Jaiaid 

Is this **"--dist-backend 'gloo'"** be included in the terminal command if using a **SINGLE GPU** or having just one GPU on the machine?

Is the following example command correct for SINGLE GPU?

python main.py **--dist-backend 'gloo'** -a resnet18 [imagenet-folder with train and val folders]

Is that what your new committed warning implies?

**Comment by HassanBinHaroon** [comment]
> @HassanBinHaroon yes it should be --dist-backend gloo (without the quote). You do not need to give quote for cmd line args but if in your system nccl version <2.5. It should be fine to use nccl

@Jaiaid I **do not have nccl** in my conda environment. Actually nccl is not in the requirements.txt, is it necessary to install?

**Comment by Jaiaid** [comment]
@HassanBinHaroon 
yes they should come with pytorch
yes, it should otherwise throw an error from NCCL (something like internal check error), to avoid that you have to do `--dist-backend gloo`
BTW have you tried actually using NCCL to run your code?

**Comment by HassanBinHaroon** [comment]
@Jaiaid Yes, I have tried running code --dist-backend nccl. It logs the user warning that (I think) you recently added and code executes smoothly BTW.

**Comment by HassanBinHaroon** [comment]
@Jaiaid I am using just SINGLE GPU for training. I am not forcefully adjusting the rank and It's -1 by default. The command that I have been using is "**python main.py -b 512 --dist-backend gloo -a resnet18 imagenet/**"

**Comment by Jaiaid** [comment]
@HassanBinHaroon 
If you use "python main.py -b 512 --dist-backend nccl -a resnet18 imagenet/" does it run smoothly?

**Comment by HassanBinHaroon** [comment]
> @HassanBinHaroon If you use "**python main.py -b 512 --dist-backend nccl -a resnet18 imagenet/**" does it run smoothly?

@Jaiaid Yes, it absolutely runs smoothly.
