### ISSUE TITLE
error while sampling from the VAE model

### ISSUE THREAD

**Issue by GaganNarula** [pytorch/examples#123]
Hi 
I am trying to train a variational auto-encoder as in the given example code. The training is working fine, but when I was trying out the decoder by giving it as input a random sample with the same dimensionality and prior as the original latent space (z in the paper), I ran into an error. I was testing the following method from the model:

model.decode()

This is my code and the error, any help is highly appreciated!:
`
z = torch.randn(150,16)
z.cuda()
v = Variable(z)
out = model(v)
`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-56-3ab6937f8ed6> in <module>()
      1 #test the model
      2 
----> 3 out = model.decode(v)

<ipython-input-52-10e925d72e4c> in decode(self, z)
     38     def decode(self, z):
     39         #pdb.set_trace()
---> 40         h1 = self.relu(self.fd1(z))
     41         h2 = self.relu(self.fd2(h1))
     42         h3 = self.fd3d( self.relu( self.fd3( h2 ) ) )

/home/songbird/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.pyc in __call__(self, *input, **kwargs)
    208 
    209     def __call__(self, *input, **kwargs):
--> 210         result = self.forward(*input, **kwargs)
    211         for hook in self._forward_hooks.values():
    212             hook_result = hook(self, input, result)

/home/songbird/anaconda2/lib/python2.7/site-packages/torch/nn/modules/linear.pyc in forward(self, input)
     52             return self._backend.Linear()(input, self.weight)
     53         else:
---> 54             return self._backend.Linear()(input, self.weight, self.bias)
     55 
     56     def __repr__(self):

/home/songbird/anaconda2/lib/python2.7/site-packages/torch/nn/_functions/linear.pyc in forward(self, input, weight, bias)
      8         self.save_for_backward(input, weight, bias)
      9         output = input.new(input.size(0), weight.size(0))
---> 10         output.addmm_(0, 1, input, weight.t())
     11         if bias is not None:
     12             # cuBLAS doesn't support 0 strides in sger, so we can't use expand

TypeError: addmm_ received an invalid combination of arguments - got (int, int, torch.FloatTensor, torch.cuda.FloatTensor), but expected one of:
 * (torch.FloatTensor mat1, torch.FloatTensor mat2)
 * (torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
 * (float beta, torch.FloatTensor mat1, torch.FloatTensor mat2)
 * (float alpha, torch.FloatTensor mat1, torch.FloatTensor mat2)
 * (float beta, torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
 * (float alpha, torch.SparseFloatTensor mat1, torch.FloatTensor mat2)
 * (float beta, float alpha, torch.FloatTensor mat1, torch.FloatTensor mat2)
 * (float beta, float alpha, torch.SparseFloatTensor mat1, torch.FloatTensor mat2)

> /home/songbird/anaconda2/lib/python2.7/site-packages/torch/nn/_functions/linear.py(10)forward()
      8         self.save_for_backward(input, weight, bias)
      9         output = input.new(input.size(0), weight.size(0))
---> 10         output.addmm_(0, 1, input, weight.t())
     11         if bias is not None:
     12             # cuBLAS doesn't support 0 strides in sger, so we can't use expand

**Comment by jekbradbury** [comment]
Looks like your input was on CPU rather than GPU.

**Comment by soumith** [comment]
Next time you need help, please use: https://discuss.pytorch.org/
