### ISSUE TITLE
'ImportError: No module named gym' after having done full install of gym in Ubuntu 14.04

### ISSUE THREAD

**Issue by NataliaDiaz** [pytorch/examples#143]
I have installed both torch and gym with

`
apt-get install -y python-numpy python-dev cmake zlib1g-dev libjpeg-dev xvfb libav-tools xorg-dev python-opengl libboost-all-dev libsdl2-dev swig
`

 what can be wrong when running 
`
/examples/reinforcement_learning$ python reinforce.py 
`
Same occurs for torch module, after it has been installed, when I run
`reinforcement_q_learning.ipynb`

**Comment by fmassa** [comment]
Did you try running `pip install -r requirements.txt` from the `reinforcement_learning` folder? It will install the requirements (including gym).

**Comment by NataliaDiaz** [comment]
Yes I did. And I get the same Error for import torch.
My version of pip: 9.01, 
Python: 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
>>> import numpy
>>> numpy.version.version
'1.12.1'
>>> import scipy
>>> scipy.version.version
'0.13.3'

**Comment by fmassa** [comment]
For installing pytorch, follow the instructions in http://pytorch.org/
Running `pip install -r requirements.txt` won't install pytorch.

**Comment by NataliaDiaz** [comment]
My mistake was that I though PyTorch was installed (I did with pip setting config) because it said all requirements were fullfilled, but it was not installed in reality. Anaconda install instead worked and fixed it. Thanks in any case!
