### ISSUE TITLE
imagenet example training gets slower over time.

### ISSUE THREAD

**Issue by zym1010** [pytorch/examples#147]
It seems that as I do training, the per batch time gets slower and slower. 

For example, when I run `CUDA_VISIBLE_DEVICES=0 python main.py -a alexnet --lr 0.01 --workers 22 /ssd/cv_datasets/ILSVRC2015/Data/CLS-LOC`.

Initially I get an average per batch time of about 0.25s

After several batches, I get 0.5s.

I `top` and find that most of memory (128GB) is occupied 

How to fix this?

**Comment by apaszke** [comment]
If that's all of your memory then the system might be swapping and the performance loss is expected. To fix it try with fewer workers or buy more RAM 😉

**Comment by zym1010** [comment]
@apaszke  thanks. but seems that the code keeps assuming more and and more memory... is that expected?

**Comment by apaszke** [comment]
No. Are you using the script from the official examples repo or is it your own?

**Comment by zym1010** [comment]
the official one.

**Comment by zym1010** [comment]
I'm now trying to reboot the computers, and see if it helps.

**Comment by zym1010** [comment]
@apaszke BTW, can you have a look at <https://discuss.pytorch.org/t/how-to-prefetch-data-when-processing-with-gpu/548/4>? I think when I'm using Caffe, this memory is not that a big issue.

**Comment by zym1010** [comment]
@apaszke I retried, and seems by checking `free -m`, it seems that, the reason of slowing down is that too many data got cached in mem (the python programs don't take much memory), and maybe the it takes time for the OS to make room for newly read images. I'm using a CentOS 6 cluster system. Maybe the caching mechanism is poor there?

**Comment by zym1010** [comment]
@apaszke I tested the same script on another machine with Ubuntu 14.04. This time, the training speed is rock solid. So I think problem is with CentOS 6.

**Comment by VictorJiangXin** [comment]
Sorry to bother you after so long time, but I have met the same problem with you. Have you solve your problem?

**Comment by zym1010** [comment]
@VictorJiangXin not sure. At least for newer OSes (not CentOS 6), this should not be a problem.
