### ISSUE TITLE
nvprof can't terminate gracefully

### ISSUE THREAD

**Issue by Stonesjtu** [pytorch/examples#155]
Running the `Word_language_model` for testing GPUs.

command:
```bash
nvprof -o profile.out python main.py --epochs 2 --cuda
```

the `nvprof` won't terminate after the training finishes. And the size of the output file `profile.out` keeps growing up.

When I press **CTRL+C**, it prints following logs:
```log
Warning: Some profiling data are not recorded. Make sure cudaProfilerStop() or cuProfilerStop() is called before application exit to flush profile data.
```

Perhaps some code in `pytorch`'s cuda backend should be modified.

**Comment by jekbradbury** [comment]
That’s way too much profile data for nvprof to handle easily; you should run with a couple of iterations, not a couple of epochs.

**Comment by Stonesjtu** [comment]
I tried with only a few batches in one single epoch, (takes ~10 secs) and it can't exit as before. Can you post your settings and the script to run a nvprof.

**Comment by suraj813** [comment]
Use the pytorch profiler instead https://github.com/pytorch/pytorch/blob/master/torch/profiler/profiler.py
