### ISSUE TITLE
Shapes in SNLI

### ISSUE THREAD

**Issue by neverfox** [pytorch/examples#158]
Looking over the SNLI example, something seems off to me. I hope I'm just missing something. First, a batch is embedded and, from the docs, I understand that Embedding layers output the shape `(N, W, D)` where N is the batch size and W is the sequence length. This is passed to the Encoder where it extracts the batch_size with `batch_size = inputs.size()[1]`. Wouldn't that give you the W and not N? Also, the inputs are passed as-is to the LSTM, which expects the shape `(W, N, D)`, but no reshaping is ever done. It seems like the Encoder is assuming `(W, N, D)` data from the start but there is never any `view` done on the embed to change the order of the dimensions, right?

**Comment by Engine-Treasure** [comment]
I have the same confusion. It seems that due to RNN's default batch second setting, the example codes suffer from some implicit problems. **The word language model does have the same shape problem.**

Can anyone give us an answer?

**Comment by openstring** [comment]
Each items in this 3-D input is a word, no matter a sentence is on a row or col, we can get the same result.
If you debug it, you will find it's tricky on reshaping, but the final shapes are correct. That's my understanding, hopefully it can help.
