### ISSUE TITLE
Request for examples on Recurrent Highway Networks (RHN)

### ISSUE THREAD

**Issue by sanyam5** [pytorch/examples#162]
Is it possible to use the existing torch.nn modules and implement RHNs? Would it make sense to have RHN as a separate module in torch.nn?

For reference, someone did raise this issue in pytorch/pytorch https://github.com/pytorch/pytorch/issues/516

**Comment by soumith** [comment]
> Is it possible to use the existing torch.nn modules and implement RHNs?

Yes.

> Would it make sense to have RHN as a separate module in torch.nn?

No, just like we dont do the same for ResNets.

**Comment by a-rodin** [comment]
@sanyam5 I wrote some time ago an example of character-level RHN: https://gist.github.com/a-rodin/d4f2ab5d7eb9d9887b26f28144e4ffdf.
