### ISSUE TITLE
why input data is not copied to CUDA memory during training (only target) ?

### ISSUE THREAD

**Issue by chahrazaddo** [pytorch/examples#166]
in ImageNet example why only target is copied to CUDA memory target.cuda(async=True)  and the absence of input.cuda() in training phase?

**Comment by apaszke** [comment]
Because `nn.DataParallel` accepts inputs that are on CPU as well. It's faster this way, because it can copy only the needed parts to each GPU.

Note that we're using GitHub issues for bug reports only, and all questions should be posted on [our forums](discuss.pytorch.org).
