### ISSUE TITLE
Regarding dimensions of mean and variance 

### ISSUE THREAD

**Issue by anindyasarkarIITH** [pytorch/examples#168]
Its a multivariate normal distribution in latent space and input space so mean(mu) and variance should be in multidimensional form(matrix) per distribution but your code is generating single value of mean and variance per distribution. So what is the math or implementation process behind it?

**Comment by Kaixhin** [comment]
Multivariate doesn't mean matrix, it just means vector. For example a 2D gaussian has 2 values, not 4. The VAE code therefore generates a 20D mean at the moment.

Theoretically the covariance could be a matrix (as off-diagonal terms would correspond to relationships between the different dimensions). However this is more difficult to deal with, so VAEs usually use a diagonal covariance matrix, hence the variance is also 20D.
