### ISSUE TITLE
imagenet example did not transfer input to gpu?

### ISSUE THREAD

**Issue by iammarvelous** [pytorch/examples#173]
In the imagenet training code, `input` is not explicitly converted to cuda in these [lines](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L163-L165). 

I've noticed that the training loader has `pin_memory` flag as True. In fact, even if a tensor has called `pin_memory()`, it is still a `FloatTensor` instead of `cuda.FloatTensor`. If I understand the [documentation](http://pytorch.org/docs/master/notes/cuda.html) correctly, the benefit of using `pin_memory()` is that you can use `async=True` in the `cuda()` method, which would be faster due to asynchronous. 

If I did not miss anything, this is a bug in the code, right?

**Comment by iammarvelous** [comment]
Apparently, there is a reason.
https://discuss.pytorch.org/t/pytorch-imagenet-github-example-training-input-variable-not-cuda/710

**Comment by 22wei22** [comment]
@iammarvelous how to get image dataset
