### ISSUE TITLE
seg fault from demo

### ISSUE THREAD

**Issue by duzeyan** [pytorch/examples#174]
When I run the example/mnist/main.py on **CPU**, there is a segment fault when batch size is greater than 4. But there is no such problem on the **GPU**.who has the same problem?

**Comment by Kaixhin** [comment]
I just ran this with `python main.py` (GPU) and `python main.py --no-cuda` (CPU), and don't have any issues, despite the batch size being 64. If you still have this error now, please try uninstalling and reinstalling torch and torchvision.

**Comment by surgan12** [comment]
I ran this python code , with batch size 500 , which is way better than 64 or 150 or 4 .
And my code is running successfully without any error and accuracy more than 99% is there
