### ISSUE TITLE
Reinforcement Examples

### ISSUE THREAD

**Issue by filmo** [pytorch/examples#180]
Ubuntu 16.04
pyTorch 0.1.12_2
gym 0.9.2

When I run both 'reinforce.py' and 'actor_critic.py' neither ever terminate. The maximum length 't' ever reported is 199 and as such it never meets the conditional > 200. (as 't' is zero-based, t=199 is actually 200 steps.)

Perhaps something has changed with the Gym environment such that it issues 'done' after 200 steps whereas it used allow it to continue to run indefinitely???? [OpenAI Gym currently defines 'solved'](https://gym.openai.com/envs/CartPole-v0) as 195 average over 100 episodes. 

I ended up changing the conditional-break to:

`if running_reward >= 195:`

from the existing:

`if running_reward > 200:`

In order to get both examples to terminate as 'solved'. (Of course the other option is that there's something horribly wrong with my setup...)

**Comment by mufeili** [comment]
I am faced with a similar issue and I agree with you about the fix. In the current [code for CartPole](https://github.com/openai/gym/blob/2b30434d14a5bd27087ae672264a9f8beb90947e/gym/envs/classic_control/cartpole.py), once `done=True`, the environment always returns a reward of 0.
