### ISSUE TITLE
ARC example

### ISSUE THREAD

**Issue by sanyam5** [pytorch/examples#211]
I've implemented Attentive Recurrent Comparators here : https://github.com/sanyam5/arc-pytorch

I would love to make a pull request to pytorch/examples. May I?

**Comment by sanyam5** [comment]
tagging @soumith

**Comment by soumith** [comment]
hey sanyam,

our metric for adding something to examples is:
- is it a baseline / standard across the community
- does it showcase good practices in situations where the other baselines dont
- is it something that folks will commonly come searching for

Based on these metrics, i dont think ARC is a good example to add.

Sorry for the delay in answering, I was on a long vacation and quite a few notifications slipped through the cracks in that time.

I think it'd be really nice to have ARC in something like: https://github.com/ritchieng/the-incredible-pytorch

We're thinking of blessing one of these lists soon and officially maintaining them.
