### ISSUE TITLE
Any example for Domain Adaptation?

### ISSUE THREAD

**Issue by redhat12345** [pytorch/examples#241]
Domain Adaptation is an interesting area at present. If any example of Domain adaptation in pytorch is available, it would be really helpful.  For an example, Deep CORAL paper is developed using caffe. The code of Deep CORAL is: 
https://github.com/VisionLearningGroup/CORAL
If this code would be available in pytorch, it would be really great.

**Comment by suraj813** [comment]
Outdated, closing
