### ISSUE TITLE
 UserWarning: RNN module weights are not part...

### ISSUE THREAD

**Issue by Robomate** [pytorch/examples#248]
Hello, on World LM model I get this user warning,
do not know what is means, so I am posting it here just to let you know.

`python3 main.py --cuda --epochs 6`

```
UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greately increasing memory usage. To compact weights again call flatten_parameters().
  output, hidden = self.rnn(emb, hidden)
```

**Comment by adelra** [comment]
can someone please explain why this issue was closed? I'm facing the same problem

**Comment by eriche2016** [comment]
same issue here

**Comment by younger26** [comment]
same issue here

**Comment by LMdeLiangMi** [comment]
same issue here

**Comment by LMdeLiangMi** [comment]
self.rnn=nn.LSTM(128,128,2)

RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greately increasing memory usage. To compact weights again call flatten_parameters().

**Comment by WilliamZhaoz** [comment]
same issue here

**Comment by lijian-1994** [comment]
@Robomate can you please explain why this issue was closed? I'm facing the same problem.Thanks!
