### ISSUE TITLE
mnist dataset(jpg format) load slow

### ISSUE THREAD

**Issue by Darknesszlx** [pytorch/examples#252]
I put different label of Mnist datasets in different folders, as is shown in attached figure.
![1510280662 1](https://user-images.githubusercontent.com/7909474/32640049-ac7d6d80-c601-11e7-9fb8-e1af8b7934f6.png)
![1510280674 1](https://user-images.githubusercontent.com/7909474/32640050-ace75998-c601-11e7-976d-583b5bae2b0b.jpg)
![1510280765 1](https://user-images.githubusercontent.com/7909474/32640051-ad239a84-c601-11e7-8eaa-7125168f0476.jpg)
 I found dataset loading is very slow compared to official example, my script is also attached!
[mnist-example.txt](https://github.com/pytorch/examples/files/1459883/mnist-example.txt)
my data load time and official example load time log
![1510281089 1](https://user-images.githubusercontent.com/7909474/32640276-e6b60e20-c602-11e7-9004-260d8b86cce6.jpg)
![1510281229 1](https://user-images.githubusercontent.com/7909474/32640277-e7ea9b8a-c602-11e7-8e32-593bb9a72fd1.jpg)

**Comment by Darknesszlx** [comment]
Also, both datasets are stored in the same HDD disk!

**Comment by hkaraoguz** [comment]
Would it be because of SSD/HDD difference? Do you have SSD?

**Comment by fmassa** [comment]
This is expected. The reason is because in the official MNIST dataset, all the data is stored in memory.
You can reduce the loading time in your case by increasing the number of threads you use to load the data.
