### ISSUE TITLE
Error For imagenet/main.py training with DistributedDataParallel().

### ISSUE THREAD

**Issue by andrew-yang0722** [pytorch/examples#253]
I got DistributedDataParallel() error.

I just fixed calling init_process_group() to pass rank like the below
dist.init_process_group(backend=args.dist_backend, init_method=args.dist_url, rank = args.rank,
                                world_size=args.world_size)

$ CUDA_VISIBLE_DEVICES=0 python main.py /dataset/imagenet_classify/ --world-size 2 --dist-backend gloo --dist-url tcp://127.0.0.1:23456 --rank 0
$ CUDA_VISIBLE_DEVICES=1 python main.py /dataset/imagenet_classify/ --world-size 2 --dist-backend gloo --dist-url tcp://127.0.0.1:23456 --rank 1

Error Message
=> creating model 'resnet18'
Traceback (most recent call last):
  File "distributed_imagenet_main.py", line 319, in <module>
    main()
  File "distributed_imagenet_main.py", line 92, in main
    model = torch.nn.parallel.DistributedDataParallel(model)
  File "/home/andrew/ml/local/lib/python2.7/site-packages/torch/nn/parallel/distributed.py", line 124, in __init__
    for param_tuple in zip(*map(lambda m: m.parameters(), self._module_copies)):
  File "/home/andrew/ml/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 262, in __getattr__
    type(self).__name__, name))
AttributeError: 'DistributedDataParallel' object has no attribute '_module_copies'
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /pytorch/torch/lib/gloo/gloo/cuda.cu:249] error == cudaSuccess. 29 vs 0. Error at: /pytorch/torch/lib/gloo/gloo/cuda.cu:249: driver shutting down
Aborted (core dumped)

What is the problem?
Is there any guild document for training ImageNet with distributed nodes?

**Comment by andrew-yang0722** [comment]
I got the above error message with 0.2.0 version.

When I build pytorch master branch.('0.4.0a0+a3bf06c')
There was no error message. It works well.
Thank you.

**Comment by minar09** [comment]
> I got the above error message with 0.2.0 version.
> 
> When I build pytorch master branch.('0.4.0a0+a3bf06c')
> There was no error message. It works well.
> Thank you.

How do you build?
