### ISSUE TITLE
Data for WikiText-2 is character, not word level, dataset

### ISSUE THREAD

**Issue by Smerity** [pytorch/examples#264]
The PyTorch word level language model has begun using the WikiText-2 dataset after licensing issues were discovered with the preprocessed Penn Treebank dataset. When the dataset was added, the raw character level dataset was added, not the word level dataset.

Hat tip to @csarofeen who noticed the vocabulary size was off.

I'll submit a pull request with the correct dataset.

**Comment by nelson-liu** [comment]
i think this can be closed now?
