### ISSUE TITLE
documentation about imagenet directory structure

### ISSUE THREAD

**Issue by donghwicha** [pytorch/examples#275]
About the directory structure for imagenet,

On the readme file linked below
https://github.com/pytorch/examples/blob/master/imagenet/README.md

> Download the ImageNet dataset and move validation images to labeled subfolders
> https://raw.githubusercontent.com/soumith/imagenetloader.torch/master/valprep.sh

To summarize above, 
creating a folder and moving image files to the folder is what's expected to do.
mkdir -p n01440764	
mv ILSVRC2012_val_00007197.JPEG n01440764/
mv ILSVRC2012_val_00009111.JPEG n01440764/	

But, on the other hand, following this code, 
https://github.com/pytorch/examples/blob/master/imagenet/main.py#L114

I only need 3 folders
- imagenet folder which contains
- train
- val

And I tried creating the latter creating 3 folder it look like working, but I am not sure if this the right way to do. 
Would there be any concrete example for directory structure? 
IMHO, just a little bit of the command line result of "ls -al:  for the folder will be enough.

**Comment by Cadene** [comment]
```
cadene@titan:/local/common-data/imagenet_2012/images$ ls
train  val

cadene@titan:/local/common-data/imagenet_2012/images$ ls val
n01440764  n01943899  n02105056  n02361337  n02843684  n03379051 ...
```

**Comment by donghwicha** [comment]
@Cadene  Thanks for the tip! I already found solution. I'm closing this thread.

**Comment by rsingh1288** [comment]
@donghwicha  can you please share what is the solution? I am also in a similar situation and wanted to know what works? Thanks in advance.
