### ISSUE TITLE
Updating expected perplexity values for WT2 in word level language model

### ISSUE THREAD

**Issue by nelson-liu** [pytorch/examples#281]
Looks like the README.md for the word level language modeling example still has the old perplexities from PTB. It'd be nice if they could be updated to WT2.
cc @Smerity  maybe?

**Comment by ajbrock** [comment]
Running just once with "python main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 40 --tied " on WT2 I get test ppl of 86.68 and valid ppl of 91.70.

**Comment by zplizzi** [comment]
Agreed, this had me stumped until I saw this issue. Running `python main.py --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 40` (with the default WT2 dataset) yields a test ppl of 94.57 and a valid ppl of 99.83.

**Comment by lixilinx** [comment]
Same issue here. Tried 'python main.py --cuda --tied', got valid ppl 105.97 and test ppl 100.33, while the one shown in readme file is 87.17. Huge gap!

**Comment by soumith** [comment]
After looking at the `git blame`, I've removed the perplexity numbers from the README entirely, as they were all the numbers for Penn-TreeBank and not WikiText2.

Closed via https://github.com/pytorch/examples/commit/97e3e13d3628b7016dc315ad64119663955c5075 and https://github.com/pytorch/examples/commit/e0929a4253f9ae6ccdde24e787788a9955fdfe1c
