### ISSUE TITLE
Super resolution: ImportError: cannot import name Resize

### ISSUE THREAD

**Issue by ykshi** [pytorch/examples#285]
When I employ the demo of Super Resolution, the error occur as:

  File "main.py", line 11, in <module>
    from data import get_training_set, get_test_set
  File "/data/yukai/pytorch/examples/super_resolution/data.py", line 5, in <module>
    from torchvision.transforms import Compose, CenterCrop, ToTensor, Resize
ImportError: cannot import name Resize

Does anyone meet this question?

**Comment by fmassa** [comment]
I believe you need to update torchvision
