### ISSUE TITLE
Batching in Word Level Language Model

### ISSUE THREAD

**Issue by mourinhoxyz** [pytorch/examples#286]
Hi,

It is not clear how does the batching happen in the Language model?

It is not clear if it the input to the model in every iteration of the loop is [seq_length, batch_size, embed_size] or [batch_size, seq_length, embed_size]?

Also, why does rnn model return output and hidden separately, they are the same... as for a rnn layer hidden itself is the output.

Thanks for the awesome library.

**Comment by dugu9sword** [comment]
http://pytorch.org/docs/master/nn.html?highlight=rnn#torch.nn.RNN

**Comment by mourinhoxyz** [comment]
@dugu9sword I am not getting how input: (seq_len, batch, input_size) will work, are we feeding sequqnces in batches? 

That is not the purpose of RNNs right? RNNs should iterate over individual words of a sentence rather than a group of words ie. a batch?

Could you explain a bit here? Thank you.

**Comment by dugu9sword** [comment]
In most cases, the first dimension of an input is 'batch'. However in a recurrent neural networks, the input are fed into the cell one by one along the "time" dimension. Thus by default the first dimension of an input to fed into RNN will be "seq_len".
However, you can specify whether the first dimension of the input is "batch" by setting `batch_first`: if True, the input and output tensors are provided as (batch, seq, feature).

**Comment by dugu9sword** [comment]
Here is an example:
```
# supposing input is (batch, seq, feature)
rnn = torch.nn.RNN(~, batch_first=True)
output=rnn(input)
```

**Comment by mourinhoxyz** [comment]
@dugu9sword thanks for the reply. when the first dimension is sequence_length, this means input is fed like: x in [seq_length, batch_size, embedding_size] ...=> x is [batch_size, embedding_size] .. which means words are not fed one by one, but instead are grouped in batches... the time dimension you mention is the same as seq_length right?

**Comment by SsnL** [comment]
Batch dimension is across different sequence. For a single sequence, the tokens are fed one by one.

**Comment by dugu9sword** [comment]
yes, the time dimension I mentioned is seq_length.
