### ISSUE TITLE
Script of training ImageNet is not correct

### ISSUE THREAD

**Issue by XiongweiWu** [pytorch/examples#291]
Hi I use your official released script to train ResNet18 on ImageNet, however the result is far away from the expected one(67.8% vs 69.75 in your model zoo) even adding color augmentation tricks. In other models as mobilenet the result is also worse than the one trained on other frameworks like caffe. I do not know whether there is sth wrong with your script. Can u give a baseline of the model trained with your script ?

**Comment by soumith** [comment]
I shall kick off a Resnet-18 run today to verify this.
To double-check, what PyTorch version are you using and how did you install it?

**Comment by XiongweiWu** [comment]
Thx for your kind help. The pytorch version is 0.4.0a0+017893e, and is installed from source. I use 4 P100 cards each with 64 images(totally 256 images/minibatch) . I add color augmentation in original script(transforms.ColorJitter(brightness=0.5, contrast=0.5, saturation=0.5, hue=0.5)) as ResNet paper said. Other settings as optimizar, learning policy are all identical to the script. The best model achieves 67.86% in ImageNet val, while released model achieves 69.65%.

**Comment by XiongweiWu** [comment]
@soumith Do u using color augmentation tricks? This is the only difference.

**Comment by soumith** [comment]
@XiongweiWu i am simply running https://github.com/pytorch/examples/tree/master/imagenet with no changes.

**Comment by soumith** [comment]
maybe your color augmentation tricks are decreasing accuracy...?

**Comment by XiongweiWu** [comment]
@soumith I think so.... I am also re-training the network without color augmentation now.

**Comment by XiongweiWu** [comment]
@soumith BTW, in principle, this step is very important since it's commonly used in many famous architectures(ResNet, Inception, DenseNet....)

**Comment by XiongweiWu** [comment]
@soumith Hi, after removing color augmentation part, mobilenet as well as resnet can be successfully reproduced. I'm so curious about that this step will hurt the training process.....

**Comment by soumith** [comment]
i think it is not beneficial to do extreme color augmentation, then network has to allocate some capacity to correct more and more weird coloring.
