### ISSUE TITLE
main.py does't save checkpoints and best model

### ISSUE THREAD

**Issue by pinkfloyd06** [pytorch/examples#292]
Hello,

l run main.py successfully l get top1 and top5 accuracy.
However l don't find any checkpoints and model saved 

thank you

**Comment by pinkfloyd06** [comment]
Hi, this one 
https://github.com/pytorch/examples/blob/master/imagenet/main.py
for imagenet with resnet18

**Comment by soumith** [comment]
I just ran it and it saves it for me. It does so in this line: https://github.com/pytorch/examples/blob/master/imagenet/main.py#L267-L270

**Comment by pinkfloyd06** [comment]
where did you specify th folder where to save best model and checkpoints ?

l run it as follow : 

python main.py --resume='/main_resnet18'

**Comment by soumith** [comment]
it is saved to the current working directory.

**Comment by pinkfloyd06** [comment]
solved

**Comment by HuangGuoHui110** [comment]
> solved
Hello, I also encountered the same problem, l don't find any checkpoints and model saved, how do you solve it, thank you!

**Comment by dqgdqg** [comment]
> > solved
> > Hello, I also encountered the same problem, l don't find any checkpoints and model saved, how do you solve it, thank you!

Me too. I ran it with the command:
`python main.py -a resnet50 --dist-url 'tcp://127.0.0.1:FREEPORT' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 [imagenet-folder with train and val folders]`
