### ISSUE TITLE
Model of the fast_neural_style can't download

### ISSUE THREAD

**Issue by ghost** [pytorch/examples#314]
In the fast_neural_style example, the trained model can't download from the link or the download_saved_models.sh script. Could you provide a new way to download the model? Very thanks!

**Comment by SsnL** [comment]
The script works. Please check if there are things like firewall that blocks downloading.

**Comment by TonyMou** [comment]
Cannot download models from dropbox. Are there any mirror links for them?

**Comment by suraj813** [comment]
The url https://www.dropbox.com/s/lrvwfehqdcxoza8/saved_models.zip?dl=1 is working
