### ISSUE TITLE
Absence of seed for result reproduction

### ISSUE THREAD

**Issue by pinkfloyd06** [pytorch/examples#327]
Hello,

When running ImageNet with different resnet architectures (18,152..) l'm not able to reproduce the results. There is a small variation in accuracy.

https://github.com/pytorch/examples/blob/master/imagenet/main.py

What is wrong ?

even by making in 
```
  main() :     
    seed=15
    torch.manual_seed(seed)
    np.random.seed(seed)
```

l don't get the same result.

Thank you for your consideration

**Comment by suraj813** [comment]
Looks like this was fixed in https://github.com/pytorch/examples/pull/381
