### ISSUE TITLE
Use pretrained word embeddings

### ISSUE THREAD

**Issue by BordiaS** [pytorch/examples#330]
I want to use my pretrained word embeddings to train this model. How do I go about implementing it? 

Thanks!

**Comment by SsnL** [comment]
This is now available with `Embedding.with_pretrained`

**Comment by josephkim583** [comment]
Can you elaborate on this? How/where do I make the changes to use the pretrained embeddings that I want to use?

**Comment by suraj813** [comment]
@josephkim583 check out the docs - the API is now `from_pretrained` https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html#torch.nn.Embedding.from_pretrained
