### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'root'

### ISSUE THREAD

**Issue by MichaelGuarin0** [pytorch/examples#334]
just a heads up

original command:
`python3 main.py --dataset lsun --dataroot lsun/` 

outputs some traceback having to do with a type error:
`Namespace(batchSize=64, beta1=0.5, cuda=False, dataroot='lsun/', dataset='lsun', imageSize=64, lr=0.0002, manualSeed=None, ndf=64, netD='', netG='', ngf=64, ngpu=1, niter=25, nz=100, outf='.', workers=2)
Random Seed:  3422
Traceback (most recent call last):
  File "main.py", line 72, in <module>
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
TypeError: __init__() got an unexpected keyword argument 'root'`

the code looks like this:
`67     dataset = dset.LSUN(root=opt.dataroot, classes=['bedroom_train'],
 68                         transform=transforms.Compose([
 69                             transforms.Resize(opt.imageSize),
 70                             transforms.CenterCrop(opt.imageSize),
 71                             transforms.ToTensor(),
 72                             transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
 73                         ]))`

maybe something changed in lsun in torchvision.dataset
`11 import torchvision.datasets as dset`

looks like this is the fix in `main.py`
` 67     dataset = dset.LSUN(opt.dataroot, classes=['bedroom_train'],`

**Comment by soumith** [comment]
@MichaelGuarin0 that is weird, `root` is what is the correct argument.
Can you update your torchvision to the latest version and re-try?
