### ISSUE TITLE
Question about 'There is an imbalance between your GPUs'

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [pytorch/examples#343]
I had a test,using the offcial example/mnist.
Change the code this way:

From:
model = Net().to(device)
To:
model = Net()
model=nn.DataParallel(model, device_ids=[0, 1]).to(device)

Then run :CUDA_VISIBLE_DEVICES=0,1 python main.py
A warning come out:

UserWarning:
There is an imbalance between your GPUs. You may want to exclude GPU 0 which
has less than 75% of the memory or cores of GPU 1. You can do so by setting
the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
environment variable.

And a error follow:
RuntimeError: after cudaLaunch in triple_chevron_launcher::launch(): out of memory

**Comment by soumith** [comment]
the example is self-explanatory. You have one powerful GPU and a weak GPU. PyTorch is suggesting that you should exclude the weak GPU using the environment variable `CUDA_VISIBLE_DEVICES`.
For example:

```
CUDA_VISIBLE_DEVICES=1 python main.py # excludes 0
```
