### ISSUE TITLE
Multiprocessing runtime error freeze_support() in Windows 64 bit 

### ISSUE THREAD

**Issue by banibrata** [pytorch/examples#352]
copied from original issue from below , but looks like it has to be fixed in this examples:

https://github.com/pytorch/pytorch/issues/7485

**Comment by ChaiZQ** [comment]
I met this problem too.
This is the output when I run dcgan example on Win10 64bit with python 3.7 with pytorch 1.1 on Anaconda.

"
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
"

But I didn't meet this on Ubuntu16.04 with python 3.5 with pytorch 1.0 on Anaconda.

**Comment by Steedalion** [comment]
Same thing using pytorch 1.7.0. This seems to be windows problem.
