### ISSUE TITLE
Super-Resolution gives me "AttributeError: module 'torch' has no attribute 'device'"

### ISSUE THREAD

**Issue by kobykotiv** [pytorch/examples#356]
Whenever I try to use the the super-resolution example I'm getting this error. But when I run other scripts that use pytorch everything is fine. 

`(pytorch) D:\____Git\super_resolution>python main.py --upscale_factor 3 --batchSize 4 --testBatchSize 100 --nEpochs 10 --lr 0.001`
```
Namespace(batchSize=4, cuda=False, lr=0.001, nEpochs=10, seed=123, testBatchSize=100, threads=4, upscale_factor=3)
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    device = torch.device("cuda" if opt.cuda else "cpu")
AttributeError: module 'torch' has no attribute 'device'
```

I'm just struggling to understand what it is I'm doing wrong. I have't modified the code. I hope this helps.

**Comment by soumith** [comment]
you are not on pytorch 0.4, you are on an older version of PyTorch

**Comment by ranjiewwen** [comment]
- when you run the mnist code you will also meet the problem ：

```
  device = torch.device("cuda" if use_cuda else "cpu")
AttributeError: 'module' object has no attribute 'device'
```

- it also is the pytorch version ??

**Comment by nzmora** [comment]
Yes, checkout the[ PyTorch 0.4 migration guide](https://pytorch.org/2018/04/22/0_4_0-migration-guide.html) and search for torch.device.

Cheers,
Neta

**Comment by janezzzz** [comment]
I use python 3.7.3 and pytorch 1.6.0 but I also met the similar attribute error.
My error here is,
AttributeError: 'torch.device' object has no attribute 'src_par_idx'.
