### ISSUE TITLE
float16 mixed precision training on Titan V is slower than float32

### ISSUE THREAD

**Issue by qigtang** [pytorch/examples#373]
Since I cannot find a place to download imagenet dataset, I modified mnist example to support float16 training, please see the code in https://github.com/qigtang/examples.git, commit ed095d384529808f930161cbf005963ad482c22a

When running in my Titan V GPU
![image](https://user-images.githubusercontent.com/7813095/41369964-34d2d178-6efb-11e8-9367-c16cca1a9b5b.png)

=======float 32 mode, ========
time python main.py

real    0m31.326s
user    1m24.282s
sys     0m19.782s

=======float 16 mode==========
time python main.py  --fp16
real    0m34.736s
user    1m23.025s
sys     0m21.134s

The float16 code is actually slower. What a surprise. 
The docker image I am using is 
nvcr.io/nvidia/pytorch      18.05-py3 

@csarofeen @nvidia 

Qustion: 
1. Does pytorch 0.4 compile half math into Volta tensorcore float16*float16  operation? 
2. Why the official nvidia mixed training document is not writing down any performance number at all?

**Comment by suraj813** [comment]
Looks outdated. Closing but reopen if you'd like to add any clarification or updated results that aren't working as expected.
