### ISSUE TITLE
trying to understand the meaning of model.train() and model.eval()

### ISSUE THREAD

**Issue by isalirezag** [pytorch/examples#376]
Hi

So i see in the main.py we have model.train() and model.val(), i dont understand how to use them. can someone explain it to me please.
For example in here: 
`python main.py -a resnet18 [imagenet-folder with train and val folders]` we did not specify train or eval, so how do we know which one to use.
I know my question is stupid, please let me know if there is any good tutorial to read and understand it.

Thanks

**Comment by soumith** [comment]
this is a question for https://discuss.pytorch.org
