### ISSUE TITLE
How to extract a trained model 

### ISSUE THREAD

**Issue by mvk07** [pytorch/examples#409]
Hi,

I have trained a model of resnet 152 using the code provided in  'examples/imagenet/main.py' I understand that it saves a checkpoint after every epoch, and at the end of the training it will save the best trained model.

My question is how can i extract this model?

**Comment by soumith** [comment]
what do you mean by "extract this model"?

**Comment by msaroufim** [comment]
I'd suggest taking a look at https://pytorch.org/docs/stable/generated/torch.save.html
