### ISSUE TITLE
RuntimeError: Found 0 images in subfolders of          in AWS

### ISSUE THREAD

**Issue by AaronFun666** [pytorch/examples#412]
Have anyone used torchvision.datasets.ImageFolder in AWS?
I met this error in predicting my pictures in my own folder

RuntimeError: Found 0 images in subfolders of: mine/1/2
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif

But, I have uploaded 3 jpg images in  mine/1/2.

It also have found the folder

Is there anything I have missed?
Any suggestion will be appreciated
<img width="371" alt="2" src="https://user-images.githubusercontent.com/42711020/45485510-cfb75c80-b74f-11e8-8ce5-bbfc05ea19ad.png">
<img width="413" alt="2 2" src="https://user-images.githubusercontent.com/42711020/45485518-d2b24d00-b74f-11e8-91b3-c5953d27b165.png">
<img width="249" alt="2 1" src="https://user-images.githubusercontent.com/42711020/45485520-d7770100-b74f-11e8-9f3b-5d0fa0b47f3b.png">

**Comment by soumith** [comment]
@AaronFun666 the "mine/1/2" folder should have subfolders, where the subfolders have images.

For example:

mine/1/2/cats/cat_1.jpg
mine/1/2/cats/cat_2.jpg
mine/1/2/cats/cat_3.jpg
mine/1/2/dogs/dog_1.jpg
mine/1/2/dogs/dog_2.jpg
mine/1/2/dogs/dog_3.jpg

**Comment by Suncheng2019** [comment]
> @AaronFun666 the "mine/1/2" folder should have subfolders, where the subfolders have images.
> 
> For example:
> 
> mine/1/2/cats/cat_1.jpg
> mine/1/2/cats/cat_2.jpg
> mine/1/2/cats/cat_3.jpg
> mine/1/2/dogs/dog_1.jpg
> mine/1/2/dogs/dog_2.jpg
> mine/1/2/dogs/dog_3.jpg

Thank you!
