### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'register_decoder'

### ISSUE THREAD

**Issue by abhinavj004** [pytorch/examples#429]
When i use the code on googlecolab ,above error is arise.

**Comment by deveshshakya** [comment]
pillow is already installed. still seeing this error.

**Comment by HaleTom** [comment]
It may be a problem with the function name:
https://github.com/python-pillow/Pillow/pull/2993

**Comment by msaroufim** [comment]
Closing, fix is to update pillow version
