### ISSUE TITLE
Ran into out of memory error for language model

### ISSUE THREAD

**Issue by fabrahman** [pytorch/examples#434]
When I run the main.py to train the language model as follow:
```
python main.py --data ./data/wikitext-103 --cuda --emsize 650 --nhid 650 --dropout 0.5 --epochs 20 --tied
```
After quite some time I ran into out of memory error, anyone has any solution? I have a Tesla k20c of RAM  4743MiB.
I also tried reducing the sequence length from 35 to 22.

```
Traceback (most recent call last):
  File "main.py", line 196, in <module>
    train()
  File "main.py", line 159, in train
    loss.backward()
  File "/home/hannahbrahman/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/hannahbrahman/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: out of memory
```

Thanks for your help

**Comment by navinAdhe** [comment]
Add batch size as an argument. Something like  "-b 15". That should do it.

**Comment by msaroufim** [comment]
I'd suggest running nvidia-smi in the background to figure out what's going on but if getting out of memory the easiest things to do are smaller batch size, smaller model, smaller input
