### ISSUE TITLE
Cannot initialize CUDA without ATen_cuda library.

### ISSUE THREAD

**Issue by josephkim583** [pytorch/examples#435]
Getting the following runtime error. 

Traceback (most recent call last):
  File "main.py", line 86, in <module>
    train_data = batchify(corpus.train, args.batch_size)
  File "main.py", line 83, in batchify
    return data.to(device)
RuntimeError: Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library.

**Comment by msaroufim** [comment]
Are you building from source, would just suggest trying out a more recent version of pytorch
