### ISSUE TITLE
Single node failure with spawn error

### ISSUE THREAD

**Issue by mdflickner** [pytorch/examples#465]
Running pytorch .4  gives error below.  This works for released 1.0.
```
++ python main.py -a resnet50 --lr 0.01 --dist-url tcp://127.0.0.1:FREEPORT --dist-backend nccl --multiprocessing-distributed imagenet
Traceback (most recent call last):
  File "main.py", line 398, in <module>
    main()
  File "main.py", line 110, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
AttributeError: module 'torch.multiprocessing' has no attribute 'spawn'
```
The error goes away and we start training if we drop the --multiprocessing-distributed option.

**Comment by mdflickner** [comment]
dup of #457

**Comment by mdflickner** [comment]
I see identical behavior with pytorch 0.4.1.post2

**Comment by zkzhu0110** [comment]
I came across the same error as this. Is this related to the version of pytorch? Thanks.

**Comment by ahmedmagdiosman** [comment]
Did anyone figure this out?

**Comment by pietern** [comment]
This is expected behavior, since `torch.multiprocessing.spawn` was added in 1.0.
