### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute 'init_process_group'

### ISSUE THREAD

**Issue by minar09** [pytorch/examples#467]
AttributeError: module 'torch.distributed' has no attribute 'init_process_group'

Still getting this error after installing latest pytorch-nightly and other stuff, when I tried to run the imagenet example script.

**Comment by TimZaman** [comment]
Same here; MacOS, Python 3.7 through pip. pytorch version 1.0.0.
```
> dir(torch.distributed)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'deprecated', 'is_available', 'torch']
```

**Comment by soumith** [comment]
the OSX binary of PyTorch does not ship with distributed support. You can check this with: `torch.distributed.is_available()` and it returns `False`

**Comment by TimZaman** [comment]
Thanks @soumith . I tried that indeed, but I was just wondering if it was documented anywhere, looked all over the place (e.g. maybe another backend would work?). Any tips on using MacOS anyway? It's mostly for convenience, dev testing.

**Comment by soumith** [comment]
Do you have multiple GPUs on your OSX machine? :O :O :O 

Right now, we dont support CUDA or multi-GPU or a few of the distributed backends (such as gloo) on OSX, but if you are inclined, compile on OSX from source and it should have `torch.distributed.deprecated` working (i.e. the old distributed backend).

**Comment by TimZaman** [comment]
I think we can close this issue.

**Comment by TimZaman** [comment]
Ran into this again on lazy sunday, looks like Pieter added this! https://github.com/pytorch/pytorch/issues/20380

**Comment by Undead-Joe** [comment]
if i have cuda but i don't want use it.how should i do?

**Comment by filipre** [comment]
There are reasons why you still want `torch.distributed` in the OSX binary. For example, when you develop a distributed program and you want to debug/test your software without setting up anything complicated. See comment form @TimZaman
>It's mostly for convenience, dev testing.
