### ISSUE TITLE
in imagenet example why the val need to first resize to 256 and then crop 224, if the input is 299 how to set the resize input?

### ISSUE THREAD

**Issue by mlinxiang** [pytorch/examples#478]
![image](https://user-images.githubusercontent.com/6283983/50218419-da286880-03c6-11e9-84a7-fc6bb57a61b1.png)
when the model is inceptionv3 the input size is 299,  while others is 224. so the resize parameter counld set to what?   and why in val stage there need to first resize to a bigger size then crop, some example directly use resize(224)

**Comment by pmeier** [comment]
> first resize to a bigger size then crop, some example directly use resize(224)

`transforms.Resize()` resizes the smallest edge to the given value. Thus, if the image is not square (`height != width`) `Resize(224)` would fail to give you an image of size `(224, 224)`.

I think the image is resized at first to make motifs roughly the same size. However, I have no clue on why or how the specific value `256` was chosen.

> inceptionv3 the input size is 299, while others is 224. so the resize parameter counld set to what?

I don't think `inception_v3` can be trained with the current implementation. If you just care about this you could change it to
```python
...
transforms.Resize(299),
transforms.CenterCrop(299),
...
```
