### ISSUE TITLE
the imagenet main when is use multi gpu(not set gpu args) then the input will not call input.cuda() why?

### ISSUE THREAD

**Issue by mlinxiang** [pytorch/examples#481]
![image](https://user-images.githubusercontent.com/6283983/50394800-c734e000-079a-11e9-89cd-964cb751a227.png)
if i do't set args.gpu, the only target.cuda() call, why do this kind, but the code run success

**Comment by soumith** [comment]
answered here: https://discuss.pytorch.org/t/pytorch-imagenet-github-example-training-input-variable-not-cuda/710
