### ISSUE TITLE
Encountered IsADirectoryError at neural style eval

### ISSUE THREAD

**Issue by HosinLau** [pytorch/examples#482]
Hello, I am new in python and machine learning related field.

I caught the following error when trying to test a style from the examples:

```
 /cygdrive/d/Downloaded Programs/git/examples/fast_neural_style
$ python neural_style/neural_style.py eval --content-image <images/content-images/amber.jpg> --model <saved_models/candy.pth> --output-image <images/output-images/> --content-scale 1 --cuda 1
Fatal Python error: init_sys_streams: can't initialize sys standard streams
IsADirectoryError: [Errno 21] Is a directory: 0
```
How can I fix this error?
Thanks for any suggestions!

**Comment by soumith** [comment]
This seems like an issue with your cygwin environment.
If you are using Windows, try using PyTorch for Windows directly rather than cygwin.
