### ISSUE TITLE
Data loading implementation

### ISSUE THREAD

**Issue by bobchennan** [pytorch/examples#49]
Is their any examples with the usage of Multiprocessing? It should be faster to use one thread or process to generate batch and manipulate the data.

**Comment by soumith** [comment]
the dcgan and imagenet examples use multiprocessed data loading.

https://github.com/pytorch/examples/blob/master/dcgan/main.py#L80-L81

The num_workers option controls that.

**Comment by bobchennan** [comment]
OK, this will be quite useful.
