### ISSUE TITLE
Changing the number of steps for word laguage example

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/examples#497]
I want to do a test for word_language example in a way that I want to use lower number of steps. Currently, it has 2983 steps and it prints one line of information after 200 steps. I can see the number of intervals, default is 200, but I can not find the number of steps.
I want to terminate after one interval.

I could find that in the code. Can somebody help?

**Comment by msaroufim** [comment]
It's this argument https://github.com/pytorch/examples/blob/main/word_language_model/main.py#L42
