### ISSUE TITLE
why you set epoch to the sampler in the distributed example?

### ISSUE THREAD

**Issue by CoinCheung** [pytorch/examples#501]
Hi,

Thanks for providing this helpful tutorial series. I am reading the part of training imagenet with distributed mode: 

At [this line](https://github.com/pytorch/examples/blob/fe8abc3c810420df2856c6e668258f396b154cee/imagenet/main.py#L208), I do not understand the reason why shall I set epoch it the sampler. What is the difference between setting the epoch or not? Cannot I directly fetch data from the dataloader with this sampler as one args?

**Comment by soumith** [comment]
it's for determinism across runs, i.e. same samples are fetched to workers across multiple runs even across distributed training.

**Comment by CoinCheung** [comment]
I tried to make my code work, thanks a lot!!

**Comment by Pluto-wei** [comment]
> I tried to make my code work, thanks a lot!!

hello! I have encountered the same problem. Is it necessary to use the sampler to scramble the data in the iter-only iteration? Will the training be misled into unhealthy states? May I ask how you solved it?
What's more, if batch_size=1, is it necessary to scramble the data?
