### ISSUE TITLE
mistake on reinforce examples

### ISSUE THREAD

**Issue by brando90** [pytorch/examples#512]
I was going through the reinforce example and noticed:

https://github.com/pytorch/examples/blob/ea825a5aa6c2db3743c803821a5e220301ebf5b4/reinforcement_learning/reinforce.py#L91

```
running_reward = running_reward * 0.99 + t * 0.01
```

which seems like a mistake. Shouldn't it be:

```
running_reward = running_reward * 0.99 + reward * 0.01
```

**Comment by soumith** [comment]
closed via https://github.com/pytorch/examples/pull/513
