### ISSUE TITLE
How to train from scratch on custom model

### ISSUE THREAD

**Issue by jennyzu** [pytorch/examples#518]
Hi,

Thank you very much for the code.
I am new to pytorch (have worked a lot with tensorflow), and have a question which is probably basic, but I can't find the answer.
If I want to train ImageNet on a model which doesn't appear in the code list (under "model names"), but I do have the model as pth.tar file, how am I able to do the training?

Thanks!

**Comment by msaroufim** [comment]
It sounds like you're using a pretrained model and would like to fine-tune it

This tutorial may help https://pytorch.org/tutorials/beginner/finetuning_torchvision_models_tutorial.html
