### ISSUE TITLE
memory inblance of GPU

### ISSUE THREAD

**Issue by zeal-github** [pytorch/examples#527]
I use the torch.distributed.launch module to multi-processing my training program. (spawn can not used in python 2.7).Everything seems fine but I don’t know why some process in 1-N gpu will has another memory usage in GPU 0.
![image](https://user-images.githubusercontent.com/40826585/54487006-07ec5300-48cb-11e9-9bcc-bdbc7483b902.png)

As depicted in the picture, the process in gpu4,6 have something in gpu0, this two usage are about 700+M memory. And sometimes other processes will also have similar behavior, but not all the other process will have memory usage in gpu0.

I don’t know why this thing happen? Since the memory unbalances, the training sometimes will be close due to 'out of memory error.

**Comment by soumith** [comment]
which example are you using?

This can happen if you initialized GPU0 before you forked, so at the time of fork both GPU0 and then later GPU6 will be initialized.

**Comment by soumith** [comment]
so if you are using python2, dont use the distributed launch utility, but use something like environment variable initialization
