### ISSUE TITLE
How to load image data if different formats

### ISSUE THREAD

**Issue by mhasnat** [pytorch/examples#53]
I am a regular caffe user and all of my datasets are prepared in lmdb format. I would like to have an example to load data of lmdb/hdf5 format? Does pytorch support it?

Thanks

**Comment by soumith** [comment]
@mhasnat you can look at https://github.com/pytorch/vision/blob/master/torchvision/datasets/lsun.py

It uses lmdb

**Comment by soumith** [comment]
in terms of examples, the DCGAN example has the option of using LSUN
