### ISSUE TITLE
Running examples/world_language_model

### ISSUE THREAD

**Issue by ohcurrent** [pytorch/examples#531]
Hello, I am trying to run 'examples/world_language_model'.
However, when I do 'python main.py --cuda' in the above directory.
It prints an error like this.
![image](https://user-images.githubusercontent.com/45330740/54750424-fa143600-4c1a-11e9-99ad-227b54d115f9.png)
Does anyone know how to solve this problem?

**Comment by sakaia** [comment]
It seems your environment is not correctly configured.
Because torch._C uses libcaffe2.so but not found it.
