### ISSUE TITLE
May be bug in imagnet/main.py

### ISSUE THREAD

**Issue by tiandunx** [pytorch/examples#533]
At line 110 in imagnet/main.py, `mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))`, but from the definition of function main_worker, i.e. `def main_worker(gpu, ngpus_per_node, args):` it accepts 3 parameters obviously, so is that OK when spawn the process? Also by default the args.gpu is None and at line 129 in imagnet/main.py,  `            args.rank = args.rank * ngpus_per_node + gpu
` variable gpu here is might be None, so it that correct?

**Comment by StefanoWoerner** [comment]
The first parameter is the rank, which is automatically passed by mp.spawn().
