### ISSUE TITLE
Hi,When I run the minist code,I have some error!

### ISSUE THREAD

**Issue by BCWang93** [pytorch/examples#536]
TypeError                                 Traceback (most recent call last)
<ipython-input-9-82fcd00ebc5b> in <module>()
     31         for img, label in test_loader:
     32                 output=model(img)
---> 33                 test_loss+=loss_fn(output, label, reduction='sum').item()
     34                 _, predict=torch.max(output.detach(), dim=1)
     35                 correct+=(predict==label).sum().item()

d:\python\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

TypeError: forward() got an unexpected keyword argument 'reduction'
Like this,I have this error,can you help me to solve it?Thank you very much

**Comment by msaroufim** [comment]
I believe this issue is now gone
