### ISSUE TITLE
Syntax error when running imagenet main.py

### ISSUE THREAD

**Issue by lcskrishna** [pytorch/examples#537]
I got the following syntax error while running imagenet main.py
Command used: 
```
% python main.py --help
```
*Error* :
```
  File "main.py", line 300
    progress.print(i)
                 ^
SyntaxError: invalid syntax
```

I'm using python 2.7 with pytorch built from source.

**Comment by jithunnair-amd** [comment]
This is an error that appears only for Py2 and not for Py3. Can someone please fix it so we can run benchmarks on both Py2 and Py3 like the earlier version did. To be clear, this is a regression in functionality.

**Comment by soumith** [comment]
this is so weird, i cant see why this is not Py2 syntax.

Does it help to add at the top of the file  `from __future__ import print_function` ?

**Comment by jithunnair-amd** [comment]
That seems to have fixed this particular error, although the script now errors out on line 377:
```
root@9b47a454adcf:/data/pytorch_examples_latest/imagenet# python main.py 
  File "main.py", line 377
    def __init__(self, num_batches, *meters, prefix=""):
                                                  ^
SyntaxError: invalid syntax
```

**Comment by pmeier** [comment]
@soumith I think I've introduced this with #529. But, just like you, I have no idea why this is a problem.
