### ISSUE TITLE
ValueError: host not found: Name or service not known

### ISSUE THREAD

**Issue by Akmazad** [pytorch/examples#540]
Hi guys,
I'm facing the following problem (while using [imagenet as an example](https://github.com/pytorch/examples/blob/master/imagenet/main.py)) and not sure if this is due to other issues in my coding. I'm using pytorch/1.1.0a0-py36, openmpi/3.1.3, cuda/9.0, dist_method="env://" and backend=nccl.
===
File "/apps/pytorch/1.1.0a0-py36/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 143, in _env_rendezvous_handler
store = TCPStore(master_addr, master_port, world_size, start_daemon)
ValueError: host not found: Name or service not known
===
Any suggestion?

**Comment by Akmazad** [comment]
solved it.

**Comment by isekulic** [comment]
@Akmazad would you mind sharing how you solved it? Thanks!

**Comment by Akmazad** [comment]
Hi 

It was quite a while ago, but as far I remember, I've made a silly mistake in the PBS script, where I submitted the job to a wrong machine, where the node architecture was different than what I was intending.

Sent from Yahoo Mail on Android 
 
  On Mon., 8 Jun. 2020 at 3:49 am, Ivan Sekulic<notifications@github.com> wrote:   


@Akmazad would you mind sharing how you solved it? Thanks!
