### ISSUE TITLE
where can I get the inference code for classification?

### ISSUE THREAD

**Issue by ShaneYS** [pytorch/examples#547]
I have trained the resnet-18 model for classification on my own dataset with examples/imagenet/main.py. And now I want to infernece the images, but there is no inference code.

**Comment by tuji-sjp** [comment]
> I have trained the resnet-18 model for classification on my own dataset with examples/imagenet/main.py. And now I want to infernece the images, but there is no inference code.

Hello, perhaps you know how to download the ImageNet dataset for this program to use?
Please tell me, thank you very much!

**Comment by tuji-sjp** [comment]
> I have trained the resnet-18 model for classification on my own dataset with examples/imagenet/main.py. And now I want to infernece the images, but there is no inference code.


Hello? Why did you close it?
I really need your help!
