### ISSUE TITLE
imagenet determinism

### ISSUE THREAD

**Issue by vchiley** [pytorch/examples#549]
Passing in a seed leads to non-deterministic training even though the flag sets:
```
        random.seed(args.seed)
        torch.manual_seed(args.seed)
        cudnn.deterministic = True
        warnings.warn('You have chosen to seed training. '
                      'This will turn on the CUDNN deterministic setting, '
                      'which can slow down your training considerably! '
                      'You may see unexpected behavior when restarting '
                      'from checkpoints.')
```
and warns the user that training will slow down.

Was there a specific design decision made for not making [cudnn.benchmark](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L193) False when the `--seed` flag is used?
Why not change [line 193 of main](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L193) to something like:
```
    cudnn.benchmark = False if args.seed else True
```

I understand that setting `cudnn.benchmark = False` will make training slower, but the user is already warned about slow training.

**Comment by soumith** [comment]
deterministic and benchmark are orthogonal. in benchmark mode one can only filter out deterministic algorithms (i cant remember if we do this in our backend or not)
