### ISSUE TITLE
Forgot to add optimizer in word_language_model/main.py? 

### ISSUE THREAD

**Issue by zizhaozhang** [pytorch/examples#55]
I didn't see optimizer used in training code. A bug?

**Comment by soumith** [comment]
no, in this example optimization was done by hand

**Comment by colesbury** [comment]
It's done on this line:

https://github.com/pytorch/examples/blob/master/word_language_model/main.py#L137

**Comment by zizhaozhang** [comment]
Opps. I miss that. Close the issue

**Comment by anandsaha** [comment]
@soumith  May I know the reason behind why it was done by hand instead of using an optimizer? Trying to get the insight.

**Comment by soumith** [comment]
just to showcase how to do by hand.
