### ISSUE TITLE
Where is the hook?

### ISSUE THREAD

**Issue by yanbixing** [pytorch/examples#554]
On the tutorial, I see it says this is an example of hook. So where is the hook?

**Comment by soumith** [comment]
which tutorial?

**Comment by yanbixing** [comment]
> which tutorial?

This one: https://pytorch.org/tutorials/beginner/former_torchies/nn_tutorial.html

**Comment by slimwangyue** [comment]
Please provide the code for hook as you mentioned in the tutorial

**Comment by soumith** [comment]
the code rendering for the tutorial seems broken. We are working on fixing it, sorry about that.
Here's the tutorial section for hooks, with code: https://pytorch.org/tutorials/beginner/former_torchies/nnft_tutorial.html#forward-and-backward-function-hooks
