### ISSUE TITLE
[ImageNet] Where is the checkpoint and best model?

### ISSUE THREAD

**Issue by dqgdqg** [pytorch/examples#557]
I ran `main.py` as follows:

`python main.py -a resnet50 --dist-url 'tcp://127.0.0.1:FREEPORT' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 [imagenet-folder with train and val folders]`

I can't find any ckpt files or model files in the current directory. 

Somebodies have the same problem. See the latest replies of this issue:
https://github.com/pytorch/examples/issues/292

**Comment by msaroufim** [comment]
#292 is solved
