### ISSUE TITLE
Function has 3 args but only give 2

### ISSUE THREAD

**Issue by xiadingZ** [pytorch/examples#558]
https://github.com/pytorch/examples/blob/5b1f45057dc14a5e2132b45233c258a1dc2a0aab/imagenet/main.py#L110

in this line, main_worker function has 3 arguments, but only give 2, is it correct?

**Comment by chrisyeh96** [comment]
I think that's how it should be:

https://pytorch.org/docs/stable/multiprocessing.html

> The function is called as fn(i, *args), where i is the process index and args is the passed through tuple of arguments.
