### ISSUE TITLE
Use official dataset for ImageNet?

### ISSUE THREAD

**Issue by pmeier** [pytorch/examples#568]
As of  version `0.3.0`,  `torchvision` [officially supports](https://github.com/pytorch/vision/blob/v0.3.0/torchvision/datasets/imagenet.py) the `ImageNet` dataset. Do we want to use it in the corresponding example?

### Cons

- We break backward compatibility for earlier `torchvision` versions

### Pros

- We can add a `download` flag, which automates the download and extraction process without any further user interference
- We can _spread the word_ that this rather famous dataset is now officially supported

I can add a PR for this if we want to do this.

**Comment by msaroufim** [comment]
In `mnist` we already use torchvision datasets so closing
