### ISSUE TITLE
help

### ISSUE THREAD

**Issue by zyj2297349886** [pytorch/examples#580]
i am a freshman.I want to test this minst and i want to use the code here.But i failed,when i use this code,what other things do i need,such as,download some other things?what should i do?

**Comment by bassbone** [comment]
@zyj2297349886 Could you tell us more specifically about your failure?

**Comment by zyj2297349886** [comment]
Thank you very much ,i was a newbie when i asked this question,now i have solved it.But still thank you for your time




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "bassbone"<notifications@github.com&gt;; 
发送时间: 2020年6月3日(星期三) 晚上10:03
收件人: "pytorch/examples"<examples@noreply.github.com&gt;; 
抄送: "Dans le ciel éclaire le gar&amp;#xE7;on"<2297349886@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [pytorch/examples] help (#580)





 
@zyj2297349886 Could you tell us more specifically about your failure?

**Comment by bassbone** [comment]
Thanks for quick reply! Can you close this issue?
