### ISSUE TITLE
Question about output word's probability

### ISSUE THREAD

**Issue by ishpiki** [pytorch/examples#588]
Hi!

I have an issue with next word prediction, because by given word and previous hidden states we could try to predict the next word. I trained the model with the default settings that you provide and on different datasets (wiki-2 and recipe dataset).I used the following functions to extract the probabilities and print the output:  
```
def print_prediction(sents):
    pred_ids = []
    idx2token = corpus.dictionary.idx2word
    predicted_words = []
    model.eval()
    hidden = model.init_hidden(1)
    output, hidden = model(sents, hidden)
    output_new = output.view(output.size(0)*output.size(1), output.size(2))
    softmaxed_head_res = torch.nn.functional.softmax(output_new, dim=-1)
    for i in softmaxed_head_res:
        values, ids = i.max(0)
        word = corpus.dictionary.idx2word[ids]
        predicted_words.append(word)
    prediction = ' '.join(predicted_words)
    print('\toriginal: ', ' '.join([idx2token[i[0]] for i in sents.tolist()]))
    print('\tpredicted: ', prediction)
```
However, output is not very good, I provide two examples for wiki-2 and recipe dataset:

recipe dataset
> **original**:  use one or a combination of asparagus broccoli carrots cauliflower celery mushrooms onions string beans
**predicted**:  a cup one cup of the and and and and and and and beans <eos>

wiki-2

> **original**:  an English film , television and theatre actor . He had a guest @-@ starring role on the television series The Bill in 2000 . This was followed by a starring role in the play Herons written by Simon Stephens , which was performed in 2001 at the Royal Court Theatre . He had a guest role in the television
	**predicted**:  <unk> @-@ , and , <unk> . , <eos> also a <unk> appearance seller <unk> in the <unk> series , <unk> and the , <eos> was the by a <unk> in in the film , . by <unk> <unk> . who was released by the . the <unk> Academy of in <eos> was previously <unk> appearance in the film series

When I used another frameworks for language modelling (e.g. TensorFlow, Keras) and the same function to predict the next words, it gives me more meaningful results. 

Maybe I should modify your code in some way for this task? 

Thanks.

**Comment by soumith** [comment]
The model that trains in pytorch/examples is a toy model, it's not intended to give good results.
If you want to look at good results, a larger model (increasing hidden size etc.) or using a more powerful model like Bert might help.

For example: https://pytorch.org/hub/huggingface_pytorch-pretrained-bert_bert/
