### ISSUE TITLE
Wrong reparametrization trick

### ISSUE THREAD

**Issue by pajola** [pytorch/examples#592]
https://github.com/pytorch/examples/blob/79d71b87d5bb46dc58da2dac5bf8289a7a2c3295/vae/main.py#L55

epsilon shouldn't be sampled from N(0, 1)?

**Comment by soumith** [comment]
@pajola i dont think so. It was fixed to it's current state by the guy who wrote the VAE paper in https://github.com/pytorch/examples/pull/419
