### ISSUE TITLE
Fivecrop/tencrop/randomcrop training performance comparison

### ISSUE THREAD

**Issue by melodyguan** [pytorch/examples#594]
Hello,
does anyone know how these different crops compare when used as data augmentation during training (e.g. on imagenet)?
1. 5 crop
2. 10 crop
3. random crop+horizontal flip (standard)
Thanks!

**Comment by edwardyehuang** [comment]
Training with random crop + horizontal flip brings more augmented data?
Using 5 or 10 crop in testing as a trick to gain a better result? (Combine the multiple results
