### ISSUE TITLE
Do you have any instructions for the use of functions related to C + + ports?

### ISSUE THREAD

**Issue by huang229** [pytorch/examples#604]
Do you have any instructions for the use of functions related to C + + ports?
for example:
auto aa = torch::tensor({ 1, 2 , 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 });
auto bb = torch::reshape(aa, { 2, 2, 2, 2 });
const void *src = bb.data<int>();
std::vector<int>value;
void *dst = &value;
torch::CopyBytes(2, src, torch::DeviceType::CPU, dst, torch::DeviceType::CPU, 0);
But I found that I could not get the desired result.
I hope to get your help. Thank you.

**Comment by soumith** [comment]
https://pytorch.org/cppdocs/

You can use https://discuss.pytorch.org/ for questions
