### ISSUE TITLE
Does this variable 'tokens' make sense?

### ISSUE THREAD

**Issue by standbyme** [pytorch/examples#607]
https://github.com/pytorch/examples/blob/4581968193699de14b56527296262dd76ab43557/word_language_model/data.py#L32

Thanks!

**Comment by sukuya** [comment]
Yes, it does. Without it,
`tokens += len(words)` which is 
`tokens = tokens + len(words)` won't work as nothing is bound to `tokens` before this.

**Comment by standbyme** [comment]
Thanks.
My statement just now may not be clear enough. What I want to say is that this variable has not been returned and can be deleted.

**Comment by sukuya** [comment]
Oh, sure.  The developer might have kept it for some debugging purpose. You can create a pull request and close the issue.

**Comment by standbyme** [comment]
@sukuya Thanks!
