### ISSUE TITLE
It's better to use Dataset

### ISSUE THREAD

**Issue by standbyme** [pytorch/examples#608]
https://github.com/pytorch/examples/blob/4581968193699de14b56527296262dd76ab43557/word_language_model/main.py#L164

If it's needed, I would like to help.

**Comment by soumith** [comment]
@zhangguanheng66 ?

**Comment by zhangguanheng66** [comment]
@standbyme Thanks. IMO, this example is to show how to build a word language model with RNN or Transformer module. We are welcome to use our dataset. 
However, unless there is a specific reason, I would like to avoid the extra dependency from the domain library.

**Comment by standbyme** [comment]
@zhangguanheng66 Thanks for your reply.
