### ISSUE TITLE
custom-dataset example: make's output: cv::imread(std::string const&, int) after having set CMAKE_PREFIX_PATH to PyTorch source directory

### ISSUE THREAD

**Issue by marcoippolito** [pytorch/examples#609]
Following the indications found here: [https://github.com/pytorch/examples/tree/master/cpp/custom-dataset](url), I first compiled PyTorch from source : [https://github.com/pytorch/pytorch#from-source](url)   :  

    marco@pc:~/pytorch$ export "USE_CUDNN=0"
    marco@pc:~/pytorch$ python setup.py install
    Building wheel torch-1.3.0a0+a671609
    -- Building version 1.3.0a0+a671609
    cmake --build . --target install --config Release -- -j 8
    [0/1] Install the project...
    -- Install configuration: "Release"
    copying third_party/pybind11/include/pybind11/pybind11.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/functional.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/cast.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/buffer_info.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/stl.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/embed.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/operators.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/attr.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/eval.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/chrono.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/detail/class.h -> torch/include/pybind11/detail
    copying third_party/pybind11/include/pybind11/detail/typeid.h -> torch/include/pybind11/detail
    copying third_party/pybind11/include/pybind11/detail/descr.h -> torch/include/pybind11/detail
    copying third_party/pybind11/include/pybind11/detail/init.h -> torch/include/pybind11/detail
    copying third_party/pybind11/include/pybind11/detail/internals.h -> torch/include/pybind11/detail
    copying third_party/pybind11/include/pybind11/detail/common.h -> torch/include/pybind11/detail
    copying third_party/pybind11/include/pybind11/iostream.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/stl_bind.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/complex.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/eigen.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/options.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/numpy.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/pytypes.h -> torch/include/pybind11
    copying third_party/pybind11/include/pybind11/common.h -> torch/include/pybind11
    running install
    running build
    running build_py
    copying torch/version.py -> build/lib.linux-x86_64-3.7/torch
    copying caffe2/proto/caffe2_pb2.py -> build/lib.linux-x86_64-3.7/caffe2/proto
    copying caffe2/proto/caffe2_legacy_pb2.py -> build/lib.linux-x86_64-3.7/caffe2/proto
    copying caffe2/proto/predictor_consts_pb2.py -> build/lib.linux-x86_64-3.7/caffe2/proto
    copying caffe2/proto/torch_pb2.py -> build/lib.linux-x86_64-3.7/caffe2/proto
    copying caffe2/proto/hsm_pb2.py -> build/lib.linux-x86_64-3.7/caffe2/proto
    copying caffe2/proto/metanet_pb2.py -> build/lib.linux-x86_64-3.7/caffe2/proto
    copying caffe2/proto/prof_dag_pb2.py -> build/lib.linux-x86_64-3.7/caffe2/proto
    running build_ext
    -- Building with NumPy bindings
    -- Not using cuDNN
    -- Not using CUDA
    -- Using MKLDNN
    -- Not using CBLAS in MKLDNN
    -- Not using NCCL
    -- Building with c10d distributed package 

    Copying extension caffe2.python.caffe2_pybind11_state
    Copying caffe2.python.caffe2_pybind11_state from torch/lib/python3.7/site-packages/caffe2/python
      caffe2_pybind11_state.cpython-37m-x86_64-linux-gnu.so to /home/marco/pytorch/build/lib.linux- 
      x86_64-3.7/caffe2/python/caffe2_pybind11_state.cpython-37m-x86_64-linux-gnu.so
    running install_lib
    copying build/lib.linux-x86_64-3.7/caffe2/proto/caffe2_pb2.py -> /home/marco/anaconda3
    /lib/python3.7/site-packages/caffe2/proto
    copying build/lib.linux-x86_64-3.7/caffe2/proto/caffe2_legacy_pb2.py -> /home/marco/anaconda3
      /lib/python3.7/site-packages/caffe2/proto
    copying build/lib.linux-x86_64-3.7/caffe2/proto/predictor_consts_pb2.py -> /home/marco
      /anaconda3/lib/python3.7/site-packages/caffe2/proto
    copying build/lib.linux-x86_64-3.7/caffe2/proto/torch_pb2.py -> /home/marco/anaconda3
      /lib/python3.7/site-packages/caffe2/proto
    copying build/lib.linux-x86_64-3.7/caffe2/proto/hsm_pb2.py -> /home/marco/anaconda3
      /lib/python3.7/site-packages/caffe2/proto
    copying build/lib.linux-x86_64-3.7/caffe2/proto/metanet_pb2.py -> /home/marco/anaconda3
      /lib/python3.7/site-packages/caffe2/proto
    copying build/lib.linux-x86_64-3.7/caffe2/proto/prof_dag_pb2.py -> /home/marco/anaconda3
      /lib/python3.7/site-packages/caffe2/proto
    copying build/lib.linux-x86_64-3.7/torch/version.py -> /home/marco/anaconda3/lib/python3.7/site-
      packages/torch
    byte-compiling /home/marco/anaconda3/lib/python3.7/site-packages/caffe2/proto/caffe2_pb2.py to 
      caffe2_pb2.cpython-37.pyc
    byte-compiling /home/marco/anaconda3/lib/python3.7/site-packages/caffe2/proto
      /caffe2_legacy_pb2.py to caffe2_legacy_pb2.cpython-37.pyc
    byte-compiling /home/marco/anaconda3/lib/python3.7/site-packages/caffe2/proto
      /predictor_consts_pb2.py to predictor_consts_pb2.cpython-37.pyc
    byte-compiling /home/marco/anaconda3/lib/python3.7/site-packages/caffe2/proto/torch_pb2.py to
      torch_pb2.cpython-37.pyc
    byte-compiling /home/marco/anaconda3/lib/python3.7/site-packages/caffe2/proto/hsm_pb2.py to 
      hsm_pb2.cpython-37.pyc
    byte-compiling /home/marco/anaconda3/lib/python3.7/site-packages/caffe2/proto/metanet_pb2.py 
      to metanet_pb2.cpython-37.pyc
    byte-compiling /home/marco/anaconda3/lib/python3.7/site-packages/caffe2/proto/prof_dag_pb2.py
      to prof_dag_pb2.cpython-37.pyc
    byte-compiling /home/marco/anaconda3/lib/python3.7/site-packages/torch/version.py to 
      version.cpython-37.pyc
    running install_egg_info
    running egg_info
    writing torch.egg-info/PKG-INFO
    writing dependency_links to torch.egg-info/dependency_links.txt
    writing entry points to torch.egg-info/entry_points.txt
    writing top-level names to torch.egg-info/top_level.txt
    reading manifest file 'torch.egg-info/SOURCES.txt'
    writing manifest file 'torch.egg-info/SOURCES.txt'
    removing '/home/marco/anaconda3/lib/python3.7/site-packages/torch-1.3.0a0+a671609-
      py3.7.egg-info' (and everything under it)
    Copying torch.egg-info to /home/marco/anaconda3/lib/python3.7/site-packages/torch-
      1.3.0a0+a671609-py3.7.egg-info
    running install_scripts
    Installing convert-caffe2-to-onnx script to /home/marco/anaconda3/bin
    Installing convert-onnx-to-caffe2 script to /home/marco/anaconda3/bin

and then set CMAKE_PREFIX_PATH to that PyTorch source directory :   

    marco@pc:~/libtorch/examples/cppExamples/custom-dataset/build$ cmake    
      -DCMAKE_PREFIX_PATH=/home/marco/pytorch ..
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/marco/libtorch/examples/cppExamples/custom-dataset
      /build
    marco@pc:~/libtorch/examples/cppExamples/custom-dataset/build$ make
    [ 50%] Linking CXX executable custom-dataset
    CMakeFiles/custom-dataset.dir/custom-dataset.cpp.o: In function `CustomDataset::get(unsigned 
    long)':
    custom-dataset.cpp:(.text._ZN13CustomDataset3getEm[_ZN13CustomDataset3getEm]+0x7f): 
      undefined reference to `cv::imread(std::string const&, int)'
    collect2: error: ld returned 1 exit status
    CMakeFiles/custom-dataset.dir/build.make:89: recipe for target 'custom-dataset' failed
    make[2]: *** [custom-dataset] Error 1
    CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/custom-dataset.dir/all' failed
    make[1]: *** [CMakeFiles/custom-dataset.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2

OS: Ubuntu 18.04.02 Server Edition
Python version: Python 3.7.4
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 

How to solve the problem?
Looking forward to your kind help.
Marco

**Comment by marcoippolito** [comment]
After removing the directory and creating a new one, this kind of problem disappeared

**Comment by januarks14** [comment]
I have the same problem. do you have done with it?

**Comment by mrdvince** [comment]
@januarks14 I had the same problem, using the cxx11 ABI version of libtorch worked for me.
