### ISSUE TITLE
word_language_model with support for Transformer model

### ISSUE THREAD

**Issue by vinutah** [pytorch/examples#613]
Hi, I think there is a bug in `generate.py`. Its an example for a word_language_model with support for Transformer model.

https://github.com/pytorch/examples/blob/6f62fcd361868406a95d71af9349f9a3d03a2c52/word_language_model/generate.py#L52 causes
```
AttributeError: 'RNNModel' object has no attribute 'model_type'
```

**Comment by joistick11** [comment]
I created a PR with supposed fix https://github.com/pytorch/examples/pull/614/
