### ISSUE TITLE
import CosineAnnealingWarmRestarts error

### ISSUE THREAD

**Issue by as754770178** [pytorch/examples#615]
I can't exec `from torch.optim.lr_scheduler import CosineAnnealingWarmRestarts`, I found this import is from `/opt/anaconda3/lib/python3.7/site-packages/torch/optim/lr_scheduler.pyi`. But I found `CosineAnnealingWarmRestarts` in `/opt/anaconda3/lib/python3.7/site-packages/torch/optim/lr_scheduler.py`.

**Comment by msaroufim** [comment]
I just tried running this in google colab and it works just fine, I'd double check if you're using a recent version of PyTorch

![Screen Shot 2022-03-09 at 4 09 55 PM](https://user-images.githubusercontent.com/3282513/157560944-4d0bc1de-30da-4d5a-bc8a-60dd51a62732.png)
