### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 26.00 MiB .................

### ISSUE THREAD

**Issue by qiahui** [pytorch/examples#621]
RuntimeError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 1024.00 MiB total capacity; 435.61 MiB already allocated; 24.17 MiB free; 26.39 MiB cached)
I have tried to set the batch-size as 16 or 32, but it didn't work. Would you please tell me how to solve this problem?

**Comment by qiahui** [comment]
> What version of PyTorch are you using? Try one or more of the following
> 
> 1. Use an even smaller batch size
> 2. Update your PyTorch version, especially if it's earlier than 1.1
> 3. Get a GPU with more than 1 GB of RAM

the Pytorch version is 1.2.0+cu92

**Comment by Drzhishi** [comment]
just try smaller batch size

**Comment by msaroufim** [comment]
Closing OP should try a newer version of PyTorch and a smaller batch size
