### ISSUE TITLE
Transformer example

### ISSUE THREAD

**Issue by mrsalehi** [pytorch/examples#635]
Hi @soumith,
It seems that there are no examples of usages of the [Transformer](https://arxiv.org/pdf/1706.03762.pdf) model in the repository. Is raising a PR for it welcomed?

**Comment by soumith** [comment]
@zhangguanheng66 is preparing a tutorial afaik, he might have opinions about examples. Doesn't word_language_model not cover MultiHeadAttention already?

**Comment by zhangguanheng66** [comment]
Just for the record, the tutorial has been landed [here](https://pytorch.org/tutorials/beginner/transformer_tutorial.html). 
The word_language_model in `pytorch/examples` repo does cover `nn.Transformer`.

**Comment by SpringRi** [comment]
> Just for the record, the tutorial has been landed [here](https://pytorch.org/tutorials/beginner/transformer_tutorial.html).
> The word_language_model in `pytorch/examples` repo does cover `nn.Transformer`.

Hi, @zhangguanheng66 , There is a [issue](https://github.com/pytorch/tutorials/issues/701)  about the tutorials/transformer_tutorial.py , but I can not mention you there, Could you help us?

I have tried the transformer model in examples/word_language_model repo, the result is same.

This is my training log for word_language_model's transformer model
```
| epoch   6 |   200/ 2983 batches | lr 5.00 | ms/batch 32.47 | loss  4.95 | ppl   140.84
| epoch   6 |   400/ 2983 batches | lr 5.00 | ms/batch 32.18 | loss  4.97 | ppl   143.44
| epoch   6 |   600/ 2983 batches | lr 5.00 | ms/batch 32.16 | loss  4.79 | ppl   120.34
| epoch   6 |   800/ 2983 batches | lr 5.00 | ms/batch 32.14 | loss  4.85 | ppl   127.16
| epoch   6 |  1000/ 2983 batches | lr 5.00 | ms/batch 32.19 | loss  4.84 | ppl   126.60
| epoch   6 |  1200/ 2983 batches | lr 5.00 | ms/batch 32.16 | loss  4.86 | ppl   128.54
| epoch   6 |  1400/ 2983 batches | lr 5.00 | ms/batch 32.17 | loss  4.91 | ppl   135.49
| epoch   6 |  1600/ 2983 batches | lr 5.00 | ms/batch 32.17 | loss  4.96 | ppl   142.61
| epoch   6 |  1800/ 2983 batches | lr 5.00 | ms/batch 32.15 | loss  4.86 | ppl   129.50
| epoch   6 |  2000/ 2983 batches | lr 5.00 | ms/batch 32.18 | loss  4.90 | ppl   133.89
| epoch   6 |  2200/ 2983 batches | lr 5.00 | ms/batch 32.17 | loss  4.79 | ppl   120.56
| epoch   6 |  2400/ 2983 batches | lr 5.00 | ms/batch 32.23 | loss  4.84 | ppl   126.53
| epoch   6 |  2600/ 2983 batches | lr 5.00 | ms/batch 32.31 | loss  4.87 | ppl   129.85
| epoch   6 |  2800/ 2983 batches | lr 5.00 | ms/batch 32.19 | loss  4.80 | ppl   121.97
-----------------------------------------------------------------------------------------
| end of epoch   6 | time: 99.66s | valid loss  5.36 | valid ppl   212.04
-----------------------------------------------------------------------------------------
=========================================================================================
| End of training | test loss  5.27 | test ppl   194.93
=========================================================================================

Thanks
```

**Comment by zhangguanheng66** [comment]
The issue reported by @SpringRi has been found (mask_filled func in pytorch v.1.3) and an issue has been created https://github.com/pytorch/pytorch/issues/28508
