### ISSUE TITLE
Do we still need to divide sample by ourselves when using a single GPU per process?

### ISSUE THREAD

**Issue by taroxd** [pytorch/examples#640]
In https://github.com/pytorch/examples/blob/ee964a2eeb41e1712fe719b83645c79bcbd0ba1a/imagenet/main.py#L149, args.batch_size is manually divided by the number of processes.

However, when I checked https://pytorch.org/docs/stable/_modules/torch/utils/data/distributed.html#DistributedSampler, I found that DistributedSampler already subsampled the batch.

Is it a bug in the imagenet example, or have I missed anything?

**Comment by qinglu0330** [comment]
I also have confusion on this particular statement. The right way I think is to divide the (global) batch size by the total number of samplers, i.e args.batch_size = int(args.batch_size / ngpus_per_node * world_size). "world_size" refers to the number of nodes (servers), not the number of total processes/GPUs.

**Comment by taroxd** [comment]
The `--batch-size` in the command line argument seems to mean "batch size per node".
