### ISSUE TITLE
How to run dcgan example?

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/examples#643]
I want to run `dcgan` example, however, the readme is not very clear.
I have downloaded classroom model from lsun as below

```
$ ls classroom_train_lmdb -lh
total 3.5G
-rw-r--r-- 1 mahmood mahmood 3.5G May  1  2015 data.mdb
-rw-r--r-- 1 mahmood mahmood  63K May  1  2015 lock.mdb
$ ls classroom_val_lmdb -lh
total 6.5M
-rw-r--r-- 1 mahmood mahmood 6.4M May  1  2015 data.mdb
-rw-r--r-- 1 mahmood mahmood  63K May  1  2015 lock.mdb
```

Now, the command is `python main.py --dataset lsun --dataroot XXX`. 
What is XXX exactly? Is it the root folder that contains `classroom_val_lmdb/` and `classroom_train_lmdb/`?

**Comment by msaroufim** [comment]
Did you use the out directory argument here? https://github.com/fyu/lsun
