### ISSUE TITLE
Reduction not declared

### ISSUE THREAD

**Issue by csverma610** [pytorch/examples#646]
Hello,
When I compile the mnist.cpp, I get the following error:

mnist.cpp:102:26: error: ‘at::Reduction’ has not been declared
                      at::Reduction::Sum)

Can someone help?

**Comment by soumith** [comment]
fixed in latest master via https://github.com/pytorch/examples/commit/4e00723456160d910092aae567a0b8daf66c49ec

Please use pytorch 1.3.0 or possibly pytorch nightly
