### ISSUE TITLE
The actual default setting of "--epochs" is not the same as the help tips

### ISSUE THREAD

**Issue by youngdou** [pytorch/examples#661]
https://github.com/pytorch/examples/blob/0634306968ed7f28e2b11b69d3b2df348b8ec53c/mnist/main.py#L78

the actual default epoch is 14, but the help tips show it's default epoch is 10

**Comment by zhangguanheng66** [comment]
It's a typo, IMO. You are welcome to submit a PR and fix the doc. Thanks.

**Comment by bassbone** [comment]
This has been fixed in #667 ! :)
