### ISSUE TITLE
what do parameters 'ndf' and 'ngf' mean?

### ISSUE THREAD

**Issue by jianzhuwang** [pytorch/examples#675]
Thanks for your code. However, I was wondering if you could tell me what 'ndf' and 'ngf' mean? I do know how these two parameters are used, but I do not know why they are called 'ndf' and 'ngf' , respectively. Looking forward to your reply.

**Comment by bentrevett** [comment]
ndf = number of filters in the discriminator
ngf = number of filters in the generator
