### ISSUE TITLE
Reading my own dataset 

### ISSUE THREAD

**Issue by gozeloglu** [pytorch/examples#676]
Hi, I want to read/load my own dataset and build my models by using these datasets. But, I did not understand how can I read/load my own dataset. All examples are using PyTorch's datasets but do not help for me. Can you help me with this problem?

**Comment by zhangguanheng66** [comment]
Which dataaset are you talking about? You may reach to a specific domain to see how to create a dataset pipeline.

**Comment by gozeloglu** [comment]
@zhangguanheng66 I want to read my own dataset which is provided by my instructor. But, I did not understand how can I read
