### ISSUE TITLE
Syntax error in run_python_examples.sh

### ISSUE THREAD

**Issue by niboshi** [pytorch/examples#685]
This script uses some bash-specific features.
It seems the shebang (currently `#!/bin/sh`) should be fixed. 
```
$ ./run_python_examples.sh 
not using cuda
./run_python_examples.sh: 30: ./run_python_examples.sh: Syntax error: "(" unexpected
```

**Comment by causten** [comment]
Using the fix from #686 the script works for me.  Not sure how to get this merged but the fix works
