### ISSUE TITLE
Add new feature to show the result of prediction 

### ISSUE THREAD

**Issue by JieunKim4578** [pytorch/examples#706]
I want to add new method to this mnist example. The motivation for this PR is to see the real result of prediction of this training model. Below is the simple blueprint of what i want to implement. Is it ok to submit these kind of method? 

```py

    def show_prediction(args, model, device, test_loader):
    model.eval()
    with torch.no_grad():
         for data, target in test_loader:
             data, target = data.to(device), target.to(device)
             plt.imshow(data[0].reshape(28, 28), cmap=cm.gray_r)
             plt.show()

             output = model(data)
             print("output[0]: ", output[0])

             pred = output.argmax(dim=1, keepdim=True)
             print("pred[0]: ", pred[0])
```

Example.
![image](https://user-images.githubusercontent.com/52270723/74081798-4916c400-4a96-11ea-9fa5-7045d2997709.png)
![image](https://user-images.githubusercontent.com/52270723/74081809-62b80b80-4a96-11ea-89d0-341b966abdbe.png)

**Comment by msaroufim** [comment]
Since main PR was also closed
