### ISSUE TITLE
Reasons for the two random generators

### ISSUE THREAD

**Issue by jayleicn** [pytorch/examples#71]
I saw the codes here, https://github.com/pytorch/examples/blob/master/mnist/main.py#L31-L33
```
torch.manual_seed(args.seed)
if args.cuda:
    torch.cuda.manual_seed(args.seed)
```
Why there are two random generators? Any reasons for using this in the design of PyTorch?

**Comment by soumith** [comment]
there are different random seeds per device (for CPU, and for each GPU). This is by design.
