### ISSUE TITLE
fast_neural_style: Error converting ONNX to CoreML

### ISSUE THREAD

**Issue by colinheye** [pytorch/examples#717]
I encounter an error converting an ONNX version of my pytorch model to CoreML. The error is caused by scale_factor in the Upsample layers of TransformerNet. It appears to be a known issue with onnx_coreml.convert, but I am wondering if there is an alternate network layer that could be used and avoid the error.

**Comment by gungorbasa** [comment]
Its actually caused by your environment. There are some inconsistencies. You should setup your environment with `python3.6`, `pytorch 1.0.1` and `torchvision 0.2.2` and your problems should fade :)
