### ISSUE TITLE
Imagenet data?

### ISSUE THREAD

**Issue by justinblaber** [pytorch/examples#753]
I'd like to use the imagenet example to train a resnet on the whole imagenet dataset... The problem is I can't seem to actually find the entire dataset anywhere (14 million images). The URLs link on the imagenet website is dead. Does anyone know the standard way to get the classification dataset? i.e. how were the pretrained models in pytorch trained?

**Comment by justinblaber** [comment]
Found out 2012 and 2017 imagenet data are the same... closing

**Comment by garmenz** [comment]
I came across the same issue. Could you share how you get the classification dataset? Thanks.

**Comment by ljz756245026** [comment]
you can download from the link

https://academictorrents.com/browse.php?search=ImageNet&page=0
