### ISSUE TITLE
Training DCGAN on CIFAR10

### ISSUE THREAD

**Issue by camhilker** [pytorch/examples#761]
Hello,

Thank you for providing the code example for DCGAN. I was able to train the GAN several times using the LSUN bedrooms dataset.

I would like to try running the code using another dataset. I was wondering if you have a link to the CIFAR10 dataset formatted for lmdb? How would I go about formatting an image dataset myself?

**Comment by msaroufim** [comment]
I'd suggest taking a look at how https://pytorch.org/vision/main/generated/torchvision.datasets.CIFAR10.html was implemented
