### ISSUE TITLE
Inconsistent batch size calculation and description in imagenet main.py

### ISSUE THREAD

**Issue by yzs981130** [pytorch/examples#771]
https://github.com/pytorch/examples/blob/b9f3b2ebb9464959bdbf0c3ac77124a704954828/imagenet/main.py#L146-L149

As above shown,  `batch_size` should be adjusted by *total number of GPUs we have*, which should be equivalent to `world_size` rather than `ngpus_per_node` according to the comments.

However, the description of `--batch-size` says it's only the sum batch size of one node as follows.

https://github.com/pytorch/examples/blob/b9f3b2ebb9464959bdbf0c3ac77124a704954828/imagenet/main.py#L39-L43

Different description seems a bit confusing when trying to keep the same batch size on single GPU between test across nodes and within one node.

**Comment by msaroufim** [comment]
@yzs981130 would you like to make a PR for this fix?

**Comment by mesllo** [comment]
Shouldn't the batch_size be divided by the world_size rather than GPUs per node? Eg. if we have 2 nodes with 4 GPUs each, shouldn't we divide batch_size by 8 rather than by 4?

**Comment by yzs981130** [comment]
> Shouldn't the batch_size be divided by the world_size rather than GPUs per node? Eg. if we have 2 nodes with 4 GPUs each, shouldn't we divide batch_size by 8 rather than by 4?

I also believe that using a global batch size as the sum of all per-GPU batch sizes is easier to understand. 

However, in this issue and #982 I just fix the annotation and make it consistent with the annotation in the argument parser (second code block above) to keep backward compatibility.
