### ISSUE TITLE
How to use my own backbone？

### ISSUE THREAD

**Issue by wangbin2018** [pytorch/examples#799]

**Comment by andics** [comment]
If you're using PyCharm, I suggest putting a break at this line and running in debug mode:
`model = models.__dict__[args.arch]()`
Then, you can see the exact naming of the sub-variables in the model and change them dynamically after loading. For example, you can reassign model.conv1 (if there is such a sub-variable) to a new conv layer of your choice.

`model.conv1 = my_conv1`
