### ISSUE TITLE
How to use a pre-trained models weights? 

### ISSUE THREAD

**Issue by stunbomb** [pytorch/examples#802]
How do we specify to use the pre-trained model? Typing in python main.py -a mobilenet_v2 is not giving me the model with pretrained weights.

**Comment by Ipsit1234** [comment]
@stunbomb you can type in the following line
`python main.py -a mobilenet_v2 --pretrained=true`

**Comment by AhmadMKhan** [comment]
just use argument --pretrained , it will download the pretrained weights and  initialises the model with it.
