### ISSUE TITLE
Recommended RAM for training ResNeXt-101?

### ISSUE THREAD

**Issue by AlexMetsai** [pytorch/examples#821]
I am training a ResNeXt-101 model in an end-to-end manner on a version of ImageNet with 13k classes (using the method presented of the ImageNet Shuffle paper). This version contains around 12 M images. My machine has a single NVIDIA GeForce RTX 2080, intel i5 9400 and 16 GB of RAM. I am deploying 4 workers for this task. It seems that I don't get the best GPU utilization, since GPU-Util percentage ranges from 0% to 94%. Furthermore, each worker uses around 2GB of swap memory, which definitely degrades training speed/data fetch. This makes me wonder if my RAM is enough for this task. If I upgrade my RAM to 32 GB, am I expected to get a significant performance boost?

Thanks!!

**Comment by msaroufim** [comment]
I just checked the original paper and it doesn't make it too clear how much RAM is actually needed https://arxiv.org/abs/1611.05431

Best way is generally to benchmark and see, the PyTorch profiler may help you debug obvious issues https://pytorch.org/blog/introducing-pytorch-profiler-the-new-and-improved-performance-tool/
