### ISSUE TITLE
Option mislabeled in VAE example

### ISSUE THREAD

**Issue by rjkilpatrick** [pytorch/examples#827]
Option `--no-cuda` **disables** CUDA training, also in README.md

https://github.com/pytorch/examples/blob/a5de3ce4da81bacc21864ace40dbc8a2e810df5a/vae/main.py#L16-L17
https://github.com/pytorch/examples/blob/a5de3ce4da81bacc21864ace40dbc8a2e810df5a/vae/README.md#L16

Suggested to change to `disables CUDA training`

**Comment by Bhuvan-21** [comment]
Can I work on this?

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/examples/commit/599654abf5ead6230dfa166133b067189a1b9275
