### ISSUE TITLE
imagenet how to download the classicication dataset?

### ISSUE THREAD

**Issue by henbucuoshanghai** [pytorch/examples#830]

**Comment by Coderx7** [comment]
You can download from the official site [here](http://image-net.org/download) (you need to register and verified)
or you can download the training set provided to the Academic torrents [Here](https://academictorrents.com/browse.php?search=ImageNet)

**Comment by henbucuoshanghai** [comment]
register and verified     I must be use a  @edu email?

**Comment by Coderx7** [comment]
@henbucuoshanghai Yes a university email would do . if you dont you can just download the torrents. They are official and with permissions granted from the official site I belive. Academic torrents is not some shady, Copy right infringement website. its supported by lots of universities including Stanford, MIT, etc.
