### ISSUE TITLE
word language model missing optimizer

### ISSUE THREAD

**Issue by guillefix** [pytorch/examples#831]
I was trying to train a Transformer on my data based on this example https://github.com/pytorch/examples/blob/master/word_language_model/main.py, and it seems that the training is missing the optimizer in the example?

**Comment by soumith** [comment]
it's because the example wrote it's own optimizer in-line: https://github.com/pytorch/examples/blob/2c57b0011a096aef83da3b5265a14db2f80cb124/word_language_model/main.py#L180-L185
