### ISSUE TITLE
License of the fast-neural-style models?

### ISSUE THREAD

**Issue by pmeier** [pytorch/examples#837]
Are the fast-neural-style models that are downloadable through

https://github.com/pytorch/examples/blob/0f0c9131ca5c79d1332dce1f4c06fe942fbdc665/fast_neural_style/download_saved_models.py#L27

also licensed under the [BSD-3-Clause license](https://github.com/pytorch/examples/blob/master/LICENSE)?

**Comment by pmeier** [comment]
@abhiskk Do you have insights about this since you contributed the models?

**Comment by abhiskk** [comment]
Hi @pmeier, yes I believe the models should licensed under the same license file as the pytorch examples repo which is BSD-3-Clause

**Comment by pmeier** [comment]
Thanks for the input @abhiskk!
