### ISSUE TITLE
Slow distributed imagenet training with Alexnet/Vgg-style networks

### ISSUE THREAD

**Issue by bradezard131** [pytorch/examples#850]
Whenever I try to train an alexnet or vgg-style network (I was trying to do VGG-F but I have confirmed that the issue persists with `torchvision.models.alexnet` and similar), the training time slows significantly under the distributed setting. Single node gives "Time" around 0.300 and "Data" around "0.001", but immediately when going to two nodes (separate machines) "Time" shoots up to > 5.000 ("Data" still ~0.001).  I tried the same thing with Resnet18 and no such issues, so I think this must be an issue with this style of network but I can't for the life of me think of why

**Comment by soumith** [comment]
they probably have too many parameters in their Linear layers and network bandwidth is the bottleneck.

Put the DDP only around the Convolutional trunk (that big Sequential) and see if that helps
