### ISSUE TITLE
Multiprocessing-distributed for a single node and multiple GPU does not work

### ISSUE THREAD

**Issue by sdamadi** [pytorch/examples#852]
https://github.com/pytorch/examples/blob/a3f28a26851867b314f4471ec6ca1c2c048217f1/imagenet/main.py#L103

Although we can use DataParallel to utilize multiple GPU's on a single machine, the documentation and the help on `--multiprocessing-distributed` says DistrubutedDataParallel is the faster one. Unfortunately, it does not work.

**Comment by Kyrie10favor** [comment]
try command like this:
`python main.py --dist-url 'tcp://127.0.0.1:9002' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 '/home/kkkkk/datasets/mini-WebFace'`
