### ISSUE TITLE
why multiple token embedding by math.sqrt(self.ninp)?

### ISSUE THREAD

**Issue by lihuiknight** [pytorch/examples#854]
Dear author, 

I am wondering why you multiple token's embedding by math.sqrt(self.ninp) in [model.py](https://github.com/pytorch/examples/blob/a3f28a26851867b314f4471ec6ca1c2c048217f1/word_language_model/model.py#L148) from the word_language_model example.

Best

**Comment by DanielFPerez** [comment]
Check the original "Attention is all you need" paper (https://arxiv.org/pdf/1706.03762.pdf) in section 3.4, the authors did this multiplication.
