### ISSUE TITLE
About the output format

### ISSUE THREAD

**Issue by Huhaowen0130** [pytorch/examples#858]
![image](https://user-images.githubusercontent.com/54608650/102691472-cd55de00-4247-11eb-98b6-c3cb33bd003a.png)
Hello, could you please tell me what do 6.25 and 0.56 mean in this picture, thank you!

**Comment by msaroufim** [comment]
The first number Accuracy at 5 means that any of your model 5 highest probability answers must match the expected answer you can see exactly how this is implemented here https://github.com/pytorch/examples/blob/886b74e17ce2df1397f363fdb9a3f940dcec03ba/imagenet/main.py#L388

Feel free to add print statements to get more intuition
