### ISSUE TITLE
In DCGAN example, when training G, D is not freezed

### ISSUE THREAD

**Issue by fxia22** [pytorch/examples#86]
Unlike in GAN paper, there is no 
```
for p in netD.parameters():
    p.requires_grad = False # to avoid computation
```
when updating generator. Is this on purpose or by mistake?

In @soumith's  torch reference implementation, D is fixed when updating G:
```
   local df_do = criterion:backward(output, label)
   local df_dg = netD:updateGradInput(input, df_do)
   netG:backward(noise, df_dg)
```

**Comment by soumith** [comment]
oh, i kinda didn't do it in hindsight, I should do it.
However that will only save computation. 
D is still frozen because I dont call optimizerD.step() (which is when D's parameters actually get updated)

**Comment by fxia22** [comment]
Thanks, that makes sense.
