### ISSUE TITLE
Structure of train_loader

### ISSUE THREAD

**Issue by Silvia-Sciva** [pytorch/examples#866]
Hi and thanks in advice for your help! I would like to upload my own set of images and to train the variational autoencoder model with my training set. I don't understand what is the structure of your train_loader. I see you use torch.utils.data.DataLoader on datasets.MNIST to obtain train_loader, but I don't understand if train_loader is the list of the images represented as numpy array or what else.

**Comment by nik-sm** [comment]
You could have a look at https://pytorch.org/docs/stable/torchvision/datasets.html#imagefolder. That dataset requires your images to be laid out in subfolders, each one containing a single class - if you don't have any classes, you can just make a single dummy folder containing all your images.

In general though, you'll need to construct a `Dataset` that describes how to grab each image (by providing a `__getitem__` function describing how to grab a single image, or an `__iter__` function describing how to iterate through all the images), and then you'll fetch batches from this using a `DataLoader`.

These tutorials explain things very nicely and might help you:
https://pytorch.org/tutorials/beginner/data_loading_tutorial.html
https://pytorch.org/docs/stable/data.html#dataset-types (when deciding whether to use the `__getitem__` style or the `__iter__` style - I typically use the `__getitem__` style, or what they call "map-style")
