### ISSUE TITLE
Implementation of Bottle

### ISSUE THREAD

**Issue by lichengunc** [pytorch/examples#87]
Isn't the implementation of Bottle of examples/snli/model.py not finished yet?
It would be cool if we have same function of torch's nn.Bottle( ) which allows varying dimensionality input. :-)

**Comment by bmccann** [comment]
I can look at that! The snli example probably needs a bigger update by now. Do you have any other suggestions?

**Comment by MrZhw** [comment]
![image](https://cloud.githubusercontent.com/assets/15373554/23609254/16ed6f94-02a8-11e7-8e84-f3d87ed5dd6c.png)
what's wrong with the Bottle?

**Comment by bmccann** [comment]
Python 3 can handle that, but python 2 cannot. I'll change it to be
compatible with both. Thanks for catching that!

**Comment by LuoweiZhou** [comment]
So, is there a function like nn.Bottle() now?

**Comment by suraj813** [comment]
Outdated now
