### ISSUE TITLE
Permissions to contribute

### ISSUE THREAD

**Issue by rbownes** [pytorch/examples#870]
Hi there, I thought I could contribute a few notebooks with really low barrier to entry for concepts like regression using tensors and for loops, small and highly documented shallow nets to illustrate concepts etc. I tried to push a notebook today to a branch I checked out for a PR but don't have permissions. How I can I request them?

**Comment by msaroufim** [comment]
You can go ahead and create a PR, no permissions are needed. Although I would suggest creating `.py` files instead since we don't have notebooks in this repo.

One way I like doing is 
```
git checkout -b my_branch
make changes
git add .
git commit -m "changes"
gh pr create
```
