### ISSUE TITLE
OpenNMT: hidden state not updated in the decoder

### ISSUE THREAD

**Issue by daahuang** [pytorch/examples#88]
Hi,

I was trying the OpenNMT example.
It seems that the hidden state of the decoder is not updated for each step. [Models.py L118](https://github.com/pytorch/examples/blob/e8d5bbd22c082c4cae239afc283bef2b20d447ae/OpenNMT/onmt/Models.py#L118)

I tried changing
`output, h = self.rnn(emb_t, hidden)`
to
`output, h = self.rnn(emb_t, h)`
and added `h = hidden` before the loop.

Both training and validation perplexities improved after the change.

**Comment by khanhptnk** [comment]
This problem is still not fixed. 

https://github.com/pytorch/examples/blob/master/OpenNMT/onmt/Models.py#L118

**Comment by khanhptnk** [comment]
The problem was fixed but then was reverted. 

https://github.com/pytorch/examples/commit/fcc2ab12be6dde8a2df1d5d6d256b6ddf35468ce

**Comment by khanhptnk** [comment]
After fixing that bug, the code gets 1.5x slower.

**Comment by soumith** [comment]
this was fixed.

OpenNMT has been moved to https://github.com/OpenNMT/OpenNMT-py and will be continuing development there by the OpenNMT team and other community members.

Please send pull requests and issues over there.

Thank you.
