### ISSUE TITLE
examples/cpp/custom-dataset/  error

### ISSUE THREAD

**Issue by Willtl** [pytorch/examples#898]
I'm trying to follow the cpp custom-dataset example, however, I'm getting the folloing error:

`error: no matching function for call to ‘torch::nn::Functional::Functional(<unresolved overloaded function type>, int, const c10::nullopt_t&)’` 

Is this example working with the latest C++ Pytorch library?

**Comment by peterkim333** [comment]
SAME ERROR. 
nobody can solve this problem!

**Comment by AliKaf** [comment]
I had the same error. Replacing
`push_back(Functional(torch::log_softmax, 1));`
by
`push_back(torch::nn::LogSoftmax(1));`
might help you.

**Comment by lancerts** [comment]
fixed in https://github.com/pytorch/examples/pull/1214 via ` push_back(Functional(
        [](torch::Tensor input) { return torch::log_softmax(input, 1); }))`
