### ISSUE TITLE
pre-trained models

### ISSUE THREAD

**Issue by yyl199655** [pytorch/examples#900]
Hello, I have a question about the torchvision models:
those pre-trained models(resnet) are trained by which datasets??
    'resnet18': 'https://download.pytorch.org/models/resnet18-5c106cde.pth',
    'resnet34': 'https://download.pytorch.org/models/resnet34-333f7ec4.pth',
    'resnet50': 'https://download.pytorch.org/models/resnet50-19c8e357.pth',
    'resnet101': 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth',
    'resnet152': 'https://download.pytorch.org/models/resnet152-b121ed2d.pth',

**Comment by DhruvAwasthi** [comment]
All of these models are from [Deep Residual Learning for Image Recognition](https://arxiv.org/pdf/1512.03385.pdf).

As you can find in section 4.1 of the above research paper, these models are trained on ImageNet 2012 classification dataset of 1000 classes. The models are trained on 1.28 million training images, and  evaluated on the 50k validation images.  They also obtain a final result on the 100k test images, They evaluate both top-1 and top-5 error rates.
