### ISSUE TITLE
License file doesn't include any owner

### ISSUE THREAD

**Issue by AntoineFroger** [pytorch/examples#902]
The copyright line in the license file should include both the year **AND** owner but there is currently no owner.  See https://opensource.org/licenses/BSD-3-Clause.

**Comment by david-pa** [comment]
I'd like to take care of this, would the owner just be "Pytorch"?

**Comment by spzala** [comment]
@david-pa Thanks for your interest. I would suggest to use `Pytorch contributors` Please propose it with a PR.

**Comment by david-pa** [comment]
PR: https://github.com/pytorch/examples/pull/1266
