### ISSUE TITLE
Question on the training output of imagenet example

### ISSUE THREAD

**Issue by e96031413** [pytorch/examples#910]
![擷取](https://user-images.githubusercontent.com/30921855/117557589-fbc54000-b0a6-11eb-8334-e57423b0b5f0.JPG)

As the figure above, I am wondering the meaning inside the parentheses. Dose it mean the corresponding metric in validation?

Take ACC@1 as example, the value between the inside and outside are quite large.

Thanks.

**Comment by chases92** [comment]
> ![擷取](https://user-images.githubusercontent.com/30921855/117557589-fbc54000-b0a6-11eb-8334-e57423b0b5f0.JPG)
> 
> As the figure above, I am wondering the meaning inside the parentheses. Dose it mean the corresponding metric in validation?
> 
> Take ACC@1 as example, the value between the inside and outside are quite large.
> 
> Thanks.

Hello, I have the same problem with you. Do you know how to solve it?

**Comment by carlodizon03** [comment]
> ![擷取](https://user-images.githubusercontent.com/30921855/117557589-fbc54000-b0a6-11eb-8334-e57423b0b5f0.JPG)
> 
> As the figure above, I am wondering the meaning inside the parentheses. Dose it mean the corresponding metric in validation?
> 
> Take ACC@1 as example, the value between the inside and outside are quite large.
> 
> Thanks.

Those are the current value and average value inside the parenthesis. Take Acc@1 for example:

95.51 (89.70) 

Current Val = 95.51
Average Val = 89.70

you may check how it was calculated in this [function](https://github.com/pytorch/examples/blob/cbb760d5e50a03df667cdc32a61f75ac28e11cbf/imagenet/main.py#L376-L380)

`    def update(self, val, n=1):
        self.val = val
        self.sum += val * n
        self.count += n
        self.avg = self.sum / self.count`

**Comment by e96031413** [comment]
@carlodizon03 

Thanks for your answer.
