### ISSUE TITLE
 'RemoteModule' object has no attribute 'forward_async' Default RPC pickler does not serialize

### ISSUE THREAD

**Issue by happynoom** [pytorch/examples#921]
When I run ddp_rpc example, I got this error:
AttributeError: 'RemoteModule' object has no attribute 'forward_async' Default RPC pickler does not serialize
It seems RemoteModule has no attribute forward_async. I use pytorch version 1.8.1

**Comment by CVPaul** [comment]
I got the same question too and solve it by switch to torch1.9.0

**Comment by msaroufim** [comment]
This seems related to #976 so closing for now
