### ISSUE TITLE
ImportError: cannot import name 'RRef' from 'torch.distributed.rpc' torch 1.9.0

### ISSUE THREAD

**Issue by Rinstein** [pytorch/examples#946]
Traceback (most recent call last):
  File "D:/test/examples/distributed/rpc/rl/main.py", line 13, in <module>
    from torch.distributed.rpc import RRef, rpc_sync, rpc_async, remote
ImportError: cannot import name 'RRef' from 'torch.distributed.rpc' (C:\Users\Zero\AppData\Local\conda\conda\envs\jidi\lib\site-packages\torch\distributed\rpc\__init__.py)

**Comment by Rinstein** [comment]
My platform is win10, not suppert all api of RPC. As below issue shows:
https://github.com/pytorch/pytorch/issues/50805

**Comment by guber6666** [comment]
怎么解决
